### ISSUE TITLE
Change conda env name from `fme` to `ace`

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#1]
Currently we are using an outdated name for the conda environment. Since the conda environment is more general than just this project, we should change the naming.

**Comment by mcgibbon** [comment]
> Since the conda environment is more general than just this project

In what way? I thought this is specifically the conda environment to run the `fme` package entrypoints.

**Comment by oliverwm1** [comment]
Going to leave the conda env name as `fme`.
