### ISSUE TITLE
Availability of model trained on E3SM?

### ISSUE THREAD

**Issue by ShihengDuan** [ai2cm/ace#10]
Hi ACE team,

Thanks for publishing the code and pertained model of ACE! I wonder if the zenodo repository is for the ACE model trained on GFDL model. Is there a public version of the model trained on E3SM EAM?

**Comment by jpdunc23** [comment]
Hi @ShihengDuan, the weights for ACE-EAMv2 are available to download using this link (`ema_ckpt.tar`): https://portal.nersc.gov/archive/home/projects/e3sm/www/e3smv2-fme-dataset

There's an inference-ready 10-year valid dataset available at that link as well, but it's around 165 GB. 

Let us know if you run into any issues.

**Comment by oliverwm1** [comment]
Also, to confirm, yes the zenodo repository (https://doi.org/10.5281/zenodo.10791087) is for the ACE model trained on FV3GFS as described in https://arxiv.org/abs/2310.02074.
