### ISSUE TITLE
Append area weights to net inputs as new channel

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#102]
This is a crazy idea that I had at some point which may be worth trying once we have flexible inputs and outputs.

**Comment by oliverwm1** [comment]
Did I miss something? Don't recall seeing a result about area weights as in input.

Note when Noah was talking about "cos zenith angle" he was referring to solar zenith angle: https://en.wikipedia.org/wiki/Solar_zenith_angle

**Comment by gideonite** [comment]
Aha right -- updated, thanks!
