### ISSUE TITLE
Long inference requires large amount of memory

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#130]
I tried training a model with `prediction_steps: 1460` (i.e. year-long inference) and it crashed with GPU OOM:

```
2023-06-15T23:39:48.836381821Z Traceback (most recent call last):
2023-06-15T23:39:48.836410160Z   File "/full-model/fme/fme/fcn_training/train.py", line 336, in <module>
2023-06-15T23:39:48.836683499Z     main(
2023-06-15T23:39:48.836705049Z   File "/full-model/fme/fme/fcn_training/train.py", line 327, in main
2023-06-15T23:39:48.836736499Z     trainer.train()
2023-06-15T23:39:48.836742589Z   File "/full-model/fme/fme/fcn_training/train.py", line 163, in train
2023-06-15T23:39:48.836837178Z     inference_logs = self.inference_one_epoch()
2023-06-15T23:39:48.836857258Z   File "/full-model/fme/fme/fcn_training/train.py", line 265, in inference_one_epoch
2023-06-15T23:39:48.836925408Z     self.stepper.run_on_batch(
2023-06-15T23:39:48.836931807Z   File "/full-model/fme/fme/core/stepper.py", line 213, in run_on_batch
2023-06-15T23:39:48.836996937Z     return run_on_batch(
2023-06-15T23:39:48.837017167Z   File "/full-model/fme/fme/core/stepper.py", line 339, in run_on_batch
2023-06-15T23:39:48.837047977Z     full_target_tensor_norm = out_packer.pack(full_data_norm, axis=channel_dim)
2023-06-15T23:39:48.837054717Z   File "/full-model/fme/fme/core/packer.py", line 22, in pack
2023-06-15T23:39:48.837114916Z     return _pack(tensors, self.names, axis=axis)
2023-06-15T23:39:48.837122296Z RuntimeError: The following operation failed in the TorchScript interpreter.
2023-06-15T23:39:48.837127786Z Traceback of TorchScript (most recent call last):
2023-06-15T23:39:48.837132996Z   File "/full-model/fme/fme/core/packer.py", line 45, in _pack
2023-06-15T23:39:48.837138276Z     tensors: Dict[str, torch.Tensor], names: List[str], axis: int = 0
2023-06-15T23:39:48.837143396Z ) -> torch.Tensor:
2023-06-15T23:39:48.837148876Z     return torch.cat([tensors[n].unsqueeze(axis) for n in names], dim=axis)
2023-06-15T23:39:48.837154176Z            ~~~~~~~~~ <--- HERE
2023-06-15T23:39:48.837159966Z RuntimeError: CUDA out of memory. Tried to allocate 15.52 GiB (GPU 5; 47.54 GiB total capacity; 35.72 GiB already allocated; 11.22 GiB free; 35.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Probably we should be a bit smarter and not require allocating entire timeseries at once.

**Comment by mcgibbon** [comment]
A bit of a challenge here is that our data loader can only get full windows, there isn't a feature for getting e.g. "the 4th through 8th timesteps of each window" in a way that's consistent each time you call it, e.g. to iterate over lead time through the dataset. fcn-mip gets around this by having the low-level data loading directly in the inference loop, but we'd like to keep loading abstracted behind a data loader.

This is the important section of the inference code as we have it right now:
```
    valid_data_loader, _ = get_data_loader(
        config.validation_data,
        requirements=data_requirements,
        train=False,
    )

    aggregator = InferenceAggregator(
        record_step_20=config.n_forward_steps >= 20, log_video=config.log_video
    )
    with torch.no_grad():
        for data in valid_data_loader:
            stepper.run_on_batch(
                data,
                train=False,
                n_forward_steps=config.n_forward_steps,
                aggregator=aggregator,
            )
    step_logs = aggregator.get_inference_logs(label="inference")
    for log in step_logs:
        wandb.log(log)
        # wandb.log cannot be called more than "a few times per second"
        time.sleep(0.3)
    if config.save_prediction_files:
        ds = aggregator.get_dataset()
        # ... processing code omitted
        ds.to_netcdf(filename)
```

I'd propose we:
- update the data loader to take in an optional lead_time argument that results in consistent initial conditions if `train=False`, i.e. if the data is not shuffled. It will raise if `train=True` to avoid accidentally calling it on shuffled data.
- run the current train-on-each-batch loop for each lead time, and save the results for each lead time in netCDF files

The result of this would be an MFDataset across lead time. Here's a mock of something the code might look like, as a rough version (with unimplemented functions and probably bugs):

```
    initial_conditions: Optional[List[Mapping[str, torch.Tensor]]] = None
    next_initial_conditions = []
    first_step = True
    memory_steps = 2  # can be a configuration option
    for lead_time in range(0, config.n_forward_steps, memory_steps):
        valid_data_loader, _ = get_data_loader(
            config.validation_data,
            requirements=data_requirements,
            train=False,
            lead_time=slice(lead_time, lead_time + memory_steps + 1),  # defaults to None
        )

        aggregator = InferenceAggregator(
            record_step_20=memory_steps >= 20, log_video=config.log_video
        )
        with torch.no_grad():
            for i, data in enumerate(valid_data_loader):
                if initial_conditions is not None:
                    data = replace_initial_conditions(data, initial_conditions[i])
                result = stepper.run_on_batch(
                    data,
                    train=False,
                    n_forward_steps=memory_steps,
                    aggregator=aggregator,
                )
                next_initial_conditions.append(get_final_conditions(result))
        step_logs = aggregator.get_inference_logs(label="inference")
        for log in step_logs:
            wandb.log(log)  # will require update if we want proper time-reduced metrics
            # wandb.log cannot be called more than "a few times per second"
            time.sleep(0.3)
        if config.save_prediction_files:
            ds = aggregator.get_dataset()
            if not first_step:
                ds = ds.isel(time=slice(1, None))  # only keep initial condition for first file
            # ... processing code omitted
            filename = filename.replace(".nc", f"_{lead_time:08d}.nc")
            ds.to_netcdf(filename)
        initial_conditions = next_initial_conditions
        next_initial_conditions = []
```

I don't really like the amount of low-level logic in this, and could abstract it away further with a new class, but this makes the logic more explicit. On the other hand, this routine is mainly responsible for piping data batches, and the added complexity is all about managing and piping data batches, so maybe it's fine.

Edit: I made a really dumb omission of the `memory_steps` variable in my first write of this. Hopefully it's clearer now.

**Comment by oliverwm1** [comment]
Thanks for the proposal. I agree that approach would work, but a downside is that it would also require changes to the `Trainer.inference_one_epoch` function if we want to be able to do longer inference during our training validation step (which I think we definitely do). The approach also means this code is using `n_forward_steps/2` more memory than it needs to (assuming we can get away with just storing 2 snapshots) which might be an issue if we go to higher horizontal resolution or many more channels.

Why not make changes to the `run_on_batch` function? To me this seems the most natural place to resolve the issue we're having. Is there a reason this function must allocate full timeseries instead of just keeping at most 2 snapshots? Even for multi-step loss training, we just need to accumulate the loss right?

> fcn-mip gets around this by having the low-level data loading directly in the inference loop, but we'd like to keep loading abstracted behind a data loader.

We are building a climate model here and it seems a bit inevitable to do I/O in the inference loop in order to load forcing data and save diagnostics.

**Comment by mcgibbon** [comment]
> a downside is that it would also require changes to the Trainer.inference_one_epoch function if we want to be able to do longer inference during our training validation step (which I think we definitely do.

I think there's a level where we can make a helper function in the inference code above, and call it from both in-training and standalone inference, to avoid duplicating the "handle out-of-memory data" code between these two places.

> The approach also means this code is using n_forward_steps/2 more memory than it needs to (assuming we can get away with just storing 2 snapshots) which might be an issue if we go to higher horizontal resolution or many more channels.

Ahhhh, my code had a bug. I added an important `memory_steps` variable which is hard-coded to say we want to do... I guess it says 2 steps at a time, but you could just as easily set it to 1. `run_on_batch` itself already supports keeping only 2 snapshots. The complicated part is that you still need two loops, one over time and one over ensemble member.

The code would be a little clearer if I can loop over time first, and ensemble member second, but that approach makes it impossible to get any ensemble statistics that are a function of timestep. The approach above lets you get an ensemble mean timeseries or any other reductive timeseries (variance, skewness, ensemble average RMSE, etc.)~~, even for an ensemble where you can't fit one sample from each ensemble member (for a single lead time) in memory~~ correction: the code as written stores the "restart" snapshots for each step in memory, which makes this unsupported, but we could store/load previous-step snapshots to/from disk if we need this feature.

This new code itself can't live in `run_on_batch`, because `run_on_batch` is only allowed access to Tensor, not to data loaders, since it's responsible only for stepping the model and not for managing batches. The level one step above (the inference code and the `train_one_epoch` routine) is responsible primarily for piping data from loaders into `run_on_batch` which can step forward. But we probably do want to make a new shared interface/helper func to use the same data piping code in both places.

> We are building a climate model here and it seems a bit inevitable to do I/O in the inference loop in order to load forcing data and save diagnostics.

Yes, we do load data and do I/O in our inference loop, but we want to do this via something like `loader.load()` instead of something like `netCDF4.open_mfdataset(filename_pattern)`, so that the low-level details of the loader itself are abstracted and we can easily switch between datasets.
