### ISSUE TITLE
Update data loader to be able to open ensemble data

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#139]
The new dataset will be an ensemble of 10-year runs, with each ensemble member covering the same time period.

Therefore we can no longer simply use `netCDF4.MFDataset` to open the data.

We need to update our data loader, or write a new one, that can handle the new format of data.

**Comment by mcgibbon** [comment]
Data format output from the model runs is multiple zarrs in a single directory as described in this [design doc](https://docs.google.com/document/d/1jQ-LhtNMnxWF9C-oQgfXTcM2GpN3AEZEK9001mEfYl8/edit). These get converted into folders of netCDF files by a `compute_dataset.py` script.

**Comment by oliverwm1** [comment]
As suggested by Matt, we may be able to use the existing dataset/data loader and simply add a layer on top of this concatenating a list of them: https://pytorch.org/docs/stable/data.html#torch.utils.data.ConcatDataset
