### ISSUE TITLE
KeyError if mask variable not in statistics dataset

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#142]
Although we only used the unnormalized "mask" data in the prescriber, the stepper currently raises an error if the "mask" variable is not available in the statistics data. Should we define a new "auxiliary_names" (or something like that) that tells the stepper about data that is only needed in unnormalized form?

This issue can be seen by making a small change to the integration test, as shown in this PR: https://github.com/ai2cm/full-model/pull/173

The traceback is:
```
train.py:329: in main
    trainer = Trainer(train_config)
train.py:123: in __init__
    self.stepper = config.stepper.get_stepper(shapes, max_epochs=config.max_epochs)
../core/stepper.py:42: in get_stepper
    return SingleModuleStepper(
../core/stepper.py:106: in __init__
    self.normalizer = config.normalization.build(config.all_names)
../core/normalizer.py:38: in build
    return get_normalizer(
../core/normalizer.py:111: in get_normalizer
    means = load_Dict_from_netcdf(global_means_path, names)
../core/normalizer.py:121: in load_Dict_from_netcdf
    Dict = {c: ds.variables[c][:] for c in names}
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7f9ce0783eb0>

>   Dict = {c: ds.variables[c][:] for c in names}
E   KeyError: 'mask'

../core/normalizer.py:121: KeyError
```

**Comment by mcgibbon** [comment]
In the short-term this could be fixed by replacing `config.all_names` in `stepper.py:106` with `list(set(config.in_names).union(config.out_names))`. I'd suggest adding a `normalize_names` attribute to the `SingleModuleStepperConfig` containing this logic. `prescriber.mask_name` is not contained in input/output names unless it's there because it's also an input/output.
