### ISSUE TITLE
Enable training across multiple nodes

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#143]
With a 10x larger dataset, we will need more compute to train model to convergence and not have very long wall clock time waits. Beaker has a 40 A100 cluster which we can reserve (I've already put in a request for mid to late July). We should explore enabling training on multiple nodes.

@jpdunc23 may look into this on Perlmutter, any findings he has would be super useful.

**Comment by oliverwm1** [comment]
Here is an experiment spec for a recent beaker batch job that uses torchrun to go on multiple nodes, we should be able to do something similar: https://beaker.org/ex/01H5QYGY7596G6FS5TAHVQN48N/spec

**Comment by oliverwm1** [comment]
Here are some beaker docs: https://beaker-docs.apps.allenai.org/experiments/distributed-training.html

We may need to install "user-space InfiniBand drivers" into our image. ([example](https://github.com/allenai/docker-images/blob/38c1f19e3d828643a4afab915608c6e7113ae5c3/cuda/Dockerfile#L115-L124))

**Comment by jpdunc23** [comment]
Note that a couple of minor modifications to fme are required for distributed training: https://github.com/ai2cm/full-model/compare/main...feature/multi-node-training

Here's a multi-node example run on Perlmutter: [t05vaqqg](https://wandb.ai/ai2cm/fourcastnet-era5/runs/t05vaqqg)

It would also be nice to log utilization metrics for all GPUs across all nodes. At the moment, the metrics are only logged for the node where global rank 0 is running.

**Comment by oliverwm1** [comment]
The experiment spec linked above was generated by the `gantry run` command in this script:

https://github.com/allenai/LLM/blob/main/scripts/olmo-small-ablation-on-gantry.sh

Some more references provided by Pete Walsh here:
https://github.com/allenai/LLM/blob/main/docker/Dockerfile.gantry
https://github.com/allenai/beaker-gantry
https://beaker-docs.apps.allenai.org/experiments/distributed-training.html

**Comment by oliverwm1** [comment]
This is working. See example experiment spec here: https://github.com/ai2cm/vcm-workflow-control/blob/redo-multinode-ensemble-data/examples/fourcastnet/beaker-train-multinode.yaml
