### ISSUE TITLE
Log wall clock time per epoch as wandb metric

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#148]
Although wandb automatically logs some useful system metrics like GPU utilization, it would be useful to log additional quantities for tracking performance. In particular we want to track how long each iteration of [this loop](https://github.com/ai2cm/full-model/blob/4cc9dcdf624751ce3045d52728ff9680ae80224f/fme/fme/fcn_training/train.py#L150-L190) takes.

I suggest:
- seconds_per_epoch (wall clock seconds per epoch; this is currently logged to stdout, but would be useful to have it as a wandb metric)
- percentage_time_train (percentage of wall clock time spent doing training)
- percentage_time_validation (as above, but for validation)
- percentage_time_inference (as above, but for inference)
- percentage_time_other (not sure we need this, but could track time for all other stuff in training loop, like model checkpointing.)

**Comment by mcgibbon** [comment]
Would it be better to use an absolute time in seconds over a percentage? I think in practice we'll want to see the impact a change to the code has on these times, and it's harder to back this out from a total training time and a percentage. If needed the percentages can be derived from absolute times.

**Comment by oliverwm1** [comment]
Yeah, I think you're right.

**Comment by mcgibbon** [comment]
Made a PR for this: https://github.com/ai2cm/full-model/pull/194
