### ISSUE TITLE
Add units labels to wandb plots for metrics that have units

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#150]
This would make it much easier to interpret our wandb reports.

**Comment by brianhenn** [comment]
@mcgibbon Currently we load variable metadata (eg units) when we initialize the data loaders. We could attach this metadata to the various aggregators, and then when `get_logs` is called on each, units information could be appended to the logged artifact in the appropriate way (eg, putting it in captions for `wand.Image` and `wand.Video`, and maybe in other ways for other charts). Thoughts?

**Comment by mcgibbon** [comment]
Yeah, you could send the VariableMetadata from the training GriddedData into the aggregator on init. Just keep in mind the inference in places depends on the aggregators for raw data and then attaches metadata in its own way to save netCDFs.
