### ISSUE TITLE
Do a C48 baseline run and enable comparison with FME runs

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#151]
A C48 FV3GFS simulation is a good baseline for our FME model, so we should do this simulation. However right now it would be difficult to compare our metrics against data from such a simulation. We should think about how we could get a C48 run to show up as a wandb run to include on our reports/plots.

**Comment by spencerkclark** [comment]
The C48 FV3GFS simulation portion of this is done.  An initial condition was created by coarsening restart files from the end of the spinup period (`2021010100`) of the `0011` (validation) ensemble member on pressure levels to C48 resolution ([notebook](https://github.com/ai2cm/explore/blob/master/spencerc/2023-07-27-C48-FME-reference/2023-07-28-generate-C48-initial-condition-via-coarsening.ipynb)).  The simulation was then run for 123 months, and the output was run through the same post-processing workflow applied in ai2cm/ace#138.  Details about the simulation have been added to the [original design document](https://docs.google.com/document/d/1jQ-LhtNMnxWF9C-oQgfXTcM2GpN3AEZEK9001mEfYl8/edit#heading=h.24rngenunc95) of the 110-year dataset.

### Data locations

#### Regridded, SHT-roundtripped, zarr-converted data

- `gs://vcm-ml-raw-flexible-retention/2023-08-03-C48-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0011_2021010100/encoded_surface_type.zarr`
- `gs://vcm-ml-raw-flexible-retention/2023-08-03-C48-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0011_2021010100/fluxes_2d.zarr`
- `gs://vcm-ml-raw-flexible-retention/2023-08-03-C48-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0011_2021010100/fourcastnet_vanilla.zarr`
- `gs://vcm-ml-raw-flexible-retention/2023-08-03-C48-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0011_2021010100/full_state.zarr`
- `gs://vcm-ml-raw-flexible-retention/2023-08-03-C48-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0011_2021010100/tendencies_3d.zarr`

#### Raw C48 history files, monthly restart files, and logs

- `gfdl:/archive/Spencer.Clark/2023-08-03-C48-FME-reference-simulation/ic_0011_2021010100`

### Runtime information

- Number of cores used: 24
- Wall clock time: ~45.2 seconds per simulated day
- Gaea partition: C5
- Processor type: AMD EPYC 7H12

**Comment by oliverwm1** [comment]
Thank you @spencerkclark! This is going to be extremely useful as a baseline to give us context on our current FME skill.

**Comment by oliverwm1** [comment]
Note we have the ability to compute metrics on a reference dataset with ai2cm/full-model#216. So we just need to just actually turn the crank and compute the metrics for the C48 run. It would also be useful to compute the metrics for one of the C96 ensemble members which would give us a sense of the uncertainty in metrics just due to natural variability.

**Comment by oliverwm1** [comment]
Currently post-processing this dataset to: `gs://vcm-ml-intermediate/2023-08-08-vertically-resolved-1deg-fme-c48-baseline-dataset/ic_0011.zarr`.

Note that because the FV3GFS diagnostics do not include the initial condition, the above dataset starts at 6Z on 1 January 2021 while the validation dataset we use (ic_0011 of the C96 runs) starts at 0Z on 1 January 2021. We need to prepend the C96 initial condition to the C48 dataset so that the time coordinate aligns.

**Comment by spencerkclark** [comment]
Right, that or maybe just reindex and fill with NaNs, since filling with C96 data is not exactly correct due to coarsening.

In principle for the dynamical core prognostic variables we could use the data in the coarse restart files and run things through the same regridding / SHT roundtrip process, but I guess we don't really have a super well-defined way of arriving at what that data should be for the physics fields (other than that we expect it should be close to the coarsened C96 data from the same time).

**Comment by oliverwm1** [comment]
This run has been launched: https://beaker.org/ex/01H7XN41DBBGXV29ZQTZSYXTFJ/tasks/01H7XN41DD1J8GC30T1DH6J7JJ/job/01H7XN4J9CG6YQFMQAMMC90M10

wandb run: https://wandb.ai/ai2cm/fourcastnet/runs/0v8lip3c?workspace=user-oliverwm
