### ISSUE TITLE
Unexpected assertion error in run_on_batch

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#154]
A recent experiment failed with following assertion error. Did I misconfigure something or is this a bug?

```
35 Traceback (most recent call last):
36   File "/full-model/fme/fme/fcn_training/train.py", line 351, in <module>
37     main(
38   File "/full-model/fme/fme/fcn_training/train.py", line 342, in main
39     trainer.train()
40   File "/full-model/fme/fme/fcn_training/train.py", line 172, in train
41     inference_logs = self.inference_one_epoch()
42   File "/full-model/fme/fme/fcn_training/train.py", line 276, in inference_one_epoch
43     run_inference(
44   File "/full-model/fme/fme/fcn_training/inference/loop.py", line 108, in run_inference
45     stepped = stepper.run_on_batch(
46   File "/full-model/fme/fme/core/stepper.py", line 238, in run_on_batch
47     return run_on_batch(
48   File "/full-model/fme/fme/core/stepper.py", line 352, in run_on_batch
49     assert example_shape[1] == n_forward_steps + 1
```

Beaker experiment: https://beaker.org/ex/01H6AASNHV9B1H1MCGKPTND3C9/tasks/01H6AASNHXV6GWJ0QB1V9DTZE6/job/01H6AATV75GJWFRQ9NFQGD6ZA6

**Comment by mcgibbon** [comment]
I'm not entirely sure. It's more likely to be a bug, but I could see this error triggering in certain cases where rollout windows don't have enough data to fill them. I see this is using an older version of the code and config, I'd try with the updated version once https://github.com/ai2cm/vcm-workflow-control/pull/169 is merged.

**Comment by oliverwm1** [comment]
I hit this again: https://beaker.org/ex/01H6F3J9DE7M4N334G9XZ9JFHN/tasks/01H6F3J9DHNPJN3M8JZAXZFKSC/job/01H6F3JSXVPX8HHEDR9CC98SJW

**Comment by oliverwm1** [comment]
This seems particular to using the `XarrayDataset` loader. Here is a similar run that uses the FV3GFS/MFDataset loader which does not crash:

https://beaker.org/ex/01H6F5TPQBGB80P8ME94Y0ZBDP/tasks/01H6F5TPQDHWNEJRH1P4FRX296/job/01H6F5V4RCA583YA9JERCK2B3M

**Comment by jpdunc23** [comment]
Did this error occur in conjunction with an OOM error? I encountered it in that context, so I assumed something funky / invalid was happening.

**Comment by oliverwm1** [comment]
> Did this error occur in conjunction with an OOM error? I encountered it in that context, so I assumed something funky / invalid was happening.

I did not notice any coincident OOM issues.

**Comment by oliverwm1** [comment]
I believe this is resolved.
