### ISSUE TITLE
Long inference during training requires a lot of shared memory

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#156]
When trying to do a 2-year inference during training (i.e. once per epoch) I am getting a lot of errors like
```
2023-07-28T20:28:37.251670147Z RuntimeError: DataLoader worker (pid 19778) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
```

The errors happen during the inference step.

Example (which is already requesting 50GiB of shared memory... quite a lot). https://beaker.org/ex/01H6F340Z3ZMDVR49PT0XV6CXW/tasks/01H6F340Z545DFT0NT8K5XWWM2/job/01H6F348QZTJ6TWM3RYD4HY3MX

In context of data loading for training, I've found that requesting fewer data workers leads to less shared memory requirements. Maybe we should allow setting the num_data_workers for the inference data loader independently of the validation data loader? Currently that is not possible.

**Comment by oliverwm1** [comment]
Increasing the shared memory request to 100GiB resolved the issue, but this seems suspiciously high.

**Comment by jpdunc23** [comment]
@oliverwm1 can this be closed now with https://github.com/ai2cm/full-model/pull/221 merged?

**Comment by oliverwm1** [comment]
I think so, although haven't actually tried doing a long rollout with this merged. Anyway let's close it and can reopen if need be.
