### ISSUE TITLE
Job crashed with timeout during inference

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#166]
Despite improvements from ai2cm/full-model#227, I recently found two jobs crash with a timeout during their inference step. ([beaker experiment link](https://beaker.org/ex/01H70MKE9296Y713BZY8JYVPY9/tasks/01H70MKE94E11NJ922WX59BA4S/job/01H70MM0W045N4FED84S5DBZQB)). Also the inference, which succeeded on the first epoch, was quite slow (1580s compared to ~200s which is what I've seen previously).

Perhaps the issue is that there were two jobs running simultaneously on the same data (and initialized at the same time, so doing inference on the same data at the same time).

Solving this may be more of a meta-issue—like should we temporarily copy data from NFS to the local storage on job startup? This could leave to faster training and would resolve this issue of competing reads of the same data. Will raise this on beaker repo, since this approach would make more sense to implement via beaker.

**Comment by oliverwm1** [comment]
> Perhaps the issue is that there were two jobs running simultaneously on the same data (and initialized at the same time, so doing inference on the same data at the same time).

This hypothesis seems likely, since I restarted only one of the jobs, and this time the inference took 230s.

We need to figure out a way around this, since it is making it impossible to do hyperparameter experiments. Note that the training time is not impacted by running 1 vs 2 experiments simultaneously, it is only the inference time. In below figure, the "-v2" run is the one that was restarted.

![Screen Shot 2023-08-04 at 2 48 07 PM](https://github.com/ai2cm/ace/assets/23640870/7fac10ec-2077-4553-bb69-077eccab1875)

**Comment by mcgibbon** [comment]
I think this is an issue to loop the beaker devs into.

**Comment by oliverwm1** [comment]
This run seems to be stalled during inference: https://beaker.org/ex/01H7K4JBV986HX4TYPW3CGPFP5/tasks/01H7K4JBVBWKSWHHN3TKSANBMT/job/01H7K4JEG7H1A0MXMYGH5YYFFS

As far as I know, there is no other job currently accessing this data, so I'm not sure if it's a competing read issue.

**Comment by oliverwm1** [comment]
Hit this again during these two jobs which were running simultaneously:

https://beaker.org/ex/01H7S780FYEFXYPFPFTGE8A965/tasks/01H7S780G0S8MXD7C01296EQWE/job/01H7S7815BFTQQQA9DJ84HZ0QB

and

https://beaker.org/ex/01H7S77GFDSAPDK0W0QPN057H2/tasks/01H7S77GFF5KMND37ER8BAYW3V/job/01H7S78106T4DAW09QAC2AAAKP

**Comment by oliverwm1** [comment]
I think this is resolved by ai2cm/full-model#473. If it occurs again, we can reopen this issue.
