### ISSUE TITLE
Make inference `TimeMeanAggregator` consistent for uneven timestep segment sizes

### ISSUE THREAD

**Issue by jpdunc23** [ai2cm/ace#175]
As of https://github.com/ai2cm/full-model/pull/234, we omit the initial condition when computing global time means to avoid having one "batch" with an extra timestep. 

Paraphrasing @mcgibbon: As a more general fix, we could use .sum here instead, and add the length of the time dimension to n_batches so the division part for the mean happens at the end. This would result in the proper time mean of all observed samples (which would mean we include the initial condition because of how this gets called). Then this aggregator would have consistent behavior regardless of how it's used.

**Comment by oliverwm1** [comment]
Resolved by ai2cm/full-model#798
