### ISSUE TITLE
Improve handling of missing atmospheric fields in derived quantities

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#180]
This is quickly becoming a significant issue as the dry air mass code is used more throughout the codebase, and on different datasets. I would propose first getting ai2cm/full-model#255 merged in and then submitting a PR to refactor for this consistently across all the code.

**Comment by gideonite** [comment]
@jpdunc23 Happy to have your thoughts here

**Comment by mcgibbon** [comment]
In particular the return type of values that might not be available should be `Optional[torch.Tensor]` so that mypy ensures we have code handling the None case wherever these are accessed.
