### ISSUE TITLE
Batch loss becoming NaN

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#182]
In a recent run (orange below) using latest codebase and new dataset the batch loss becomes NaN somewhere between 700 and 800 batches seen. Not sure if this is a code issue, something wrong in the new dataset, or something else.

![Screen Shot 2023-08-11 at 3 45 48 PM](https://github.com/ai2cm/ace/assets/23640870/f5bcc86c-462c-4a96-b5a7-89d1cf105713)

**Comment by oliverwm1** [comment]
Strangely there are some time steps with NaNs in the "ic_0002" dataset for the 2030100100.nc month (based on a script I wrote to check all files).

```
Checking /net/nfs/climate/data/2023-08-11-vertically-resolved-1deg-fme-ensemble-dataset/train/ic_0002/2030100100.nc
Found a NaN in HGTsfc
Found a NaN in tendency_of_total_water_path
Found a NaN in tendency_of_total_water_path_due_to_advection
Found a NaN in total_water_path
```

**Comment by mcgibbon** [comment]
It seems surprising it has taken until now for this to cause an issue?

**Comment by oliverwm1** [comment]
This dataset was generated last Thursday (new version with surface height). Anyway, I manually reran the zarr -> netCDF conversion for that single month and that resolved this issue.
