### ISSUE TITLE
Double area weighting in calculation of mean dry air mass

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#184]
There is a bug in that dry air mass is area-weighted twice when calculated during inference. This is because inference aggregators assume all model variables are per-area. The return value of `compute_dry_air_mass` is total column dry air mass (ostensibly in kg), which we would need to sum or simple average rather than taking an area-weighted average, since area has already been weighted into the calculation.

To correct this:
- The derived metrics during inference will need to compute a per-area metric such as pressure from dry air (which would address ai2cm/ace#185), so that the area-weighted averaging in the inference aggregators is valid. I would propose we use pressure in Pa and change the name to surface_pressure_due_to_dry_air.
- `fme.core.aggregator.one_step.derived.DryAirMass` does not currently have a bug but will need to be updated to take an area-weighted average (instead of a sum) as a result of this change.

**Comment by gideonite** [comment]
Weird, I could have sworn that this had been resolved, but I guess that change got lost amidst ai2cm/full-model#255.

**Comment by gideonite** [comment]
I am going to split this into two separate issues, since they are somewhat orthogonal to each other. See ai2cm/ace#185

**Comment by gideonite** [comment]
Steps:
1. Do the actual code change, e.g. to rename in Pa simply compute `pressure_thickness - water_path`
2. Rename to `surface_pressure_due_to_dry_air`
3. Compute area weighted means in the one step aggregation code

Notably, area-weighted biases, etc. should be taken care of by the existing inference pipeline.
