### ISSUE TITLE
Sort imports automatically

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#188]
This is standard practice and should probably be incorporated into our pre-commit system.

**Comment by mcgibbon** [comment]
I'd suggest `isort` as I've used it before ([in the pace repo](https://github.com/ai2cm/pace/blob/main/.pre-commit-config.yaml) on the DSL team), open to other options. That config is out of date, up to date instructions from isort themselves are [here](https://pycqa.github.io/isort/docs/configuration/pre-commit.html). May need a flag for `black` compatibility.
