### ISSUE TITLE
Do we want validation metrics in our full inference runs?

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#189]
I just noticed these empty keys in inference. Is this already known?

[wandb](https://wandb.ai/ai2cm/fourcastnet/runs/ernspgap?workspace=user-gideond)

<img width="440" alt="image" src="https://github.com/ai2cm/ace/assets/2163686/4b2cbb6d-e1dd-4d2e-b189-ed2d34972804">

**Comment by oliverwm1** [comment]
No, we don't want these metrics for our full inference runs. They are already reported during training, so does not make sense to duplicate for inference runs (and in many cases, similar metrics are already defined for autoregressive inference).
