### ISSUE TITLE
Save "wandb.Image" diagnostics to disk during inference

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#195]
It would be useful to regenerate plots of things like time-mean maps with changed colorbars etc. Currently this data is not saved except as a wandb.Image. It would be useful to save these fields to a separate "diagnostics" netCDF file.

Specifically these come to mind:

Highest priority:
- time-mean bias maps
- time-mean gen maps

Lower priority:
- zonal mean bias time vs latitude
- zonal mean gen time vs latitude

**Comment by gideonite** [comment]
It looks like most of this occurs in the following calls. Notably, this does not include anything in snapshot (e.g. residuals).

https://github.com/ai2cm/full-model/blob/ea4b2fec80524b5b73e49a4f8f22bd7907c934d6/fme/fme/core/aggregator/inference/time_mean.py#L121

https://github.com/ai2cm/full-model/blob/ea4b2fec80524b5b73e49a4f8f22bd7907c934d6/fme/fme/core/aggregator/inference/zonal_mean.py#L111

Question: Do we want to save all the timesteps in netcdf? Or just the last one? @oliverwm1

**Comment by oliverwm1** [comment]
The time-mean maps have no time dimension. For the zonal mean plot, we should save the full time vs latitude data. Note that the zonal mean plot is lower priority so it would be fine to just implement saving the data behind the time-mean maps for now.

I don't think it's a priority to save the "snapshot" maps that are plotted in validation (I think this is what you are referring to w.r.t. timesteps?)

This module might be a useful reference. This is used to save metrics which are reduced across the sample/batch dimension. We want something similar, but for the data that is reduced across time dim: https://github.com/ai2cm/full-model/blob/main/fme/fme/fcn_training/inference/data_writer/video.py

**Comment by gideonite** [comment]
I think there's a difference though in terms of the implementation since the time-mean that we are interested should only be saved to disk when inference is complete. Or, perhaps we just keep overwriting the same file?

**Comment by oliverwm1** [comment]
> I think there's a difference though in terms of the implementation since the time-mean that we are interested should only be saved to disk when inference is complete. Or, perhaps we just keep overwriting the same file?

Got it. Yes for the time-mean maps, just writing when inference is complete makes sense to me. The time vs latitude data would make sense to append to as inference proceeds. But we could punt on implementing that for now.

**Comment by gideonite** [comment]
Right, this all makes sense. I think the "only doing when inference is complete" aspect is new to our codbasee which has thus far optimized for incremental updates to metrics, but still this shouldn't be a problem.

**Comment by oliverwm1** [comment]
> Right, this all makes sense. I think the "only doing when inference is complete" aspect is new to our codbasee which has thus far optimized for incremental updates to metrics, but still this shouldn't be a problem.

We currently do the upload of all metrics to wandb at the very end of the run (which is not totally ideal, since it misses out on taking advantage of doing async upload of metrics while inference proceeds). So in some sense this will be analogous to that step. But should be very fast since not very much data is actually being written.

**Comment by gideonite** [comment]
For, time-mean bias and time-mean gen maps, what is the final dimension? I can't seem to be able to find examples of these images on [recent wandb runs](https://wandb.ai/ai2cm/fourcastnet/runs/2g6crdes?workspace=user-gideond) (`time_mean/gen_map` appears to be empty). Do we want `(initial_condition, field, lat, lon)`?

**Comment by mcgibbon** [comment]
That wandb run is relatively old, check for example [this recent wandb inference run for EMA](https://wandb.ai/ai2cm/fourcastnet/runs/hwnppevf). I believe the dimensionality for each field is [lat, lon]. We could discuss resolving this along [ic] as well, but that's not how they're reported in wandb.

Edit: I realized I'm wading into a discussion that's been going on a while, Oli should probably be the one to answer this.

**Comment by gideonite** [comment]
Ok so we want to average over `ic`. Probably obvious but just for completeness, we do not want to average over field. So the output diagnostics netcdf should be `(field, lat, lon)`.

**Comment by mcgibbon** [comment]
You may want to check the code for the [video data writer](https://github.com/ai2cm/full-model/blob/main/fme/fme/fcn_training/inference/data_writer/video.py), as this is a very similar task.

**Comment by gideonite** [comment]
Is it actually already done [here](https://github.com/ai2cm/full-model/blob/779e47d0bd1e6755b2a8bfdd26d51d726b02ec5b/fme/fme/core/aggregator/inference/time_mean.py#L156)? That should be getting the dataset for all the time-mean fields. The writer calls that when it is [flushed](https://github.com/ai2cm/full-model/blob/779e47d0bd1e6755b2a8bfdd26d51d726b02ec5b/fme/fme/fcn_training/inference/data_writer/video.py#L68).

**Comment by mcgibbon** [comment]
Not exactly, that's an old, unused method which only grabs the float metrics (because those are all that existed when it was written). You only care about the [lat, lon] fields, not the scalar metrics (though I'm sure it's fine to also include the scalars). So you'd want to update that method to handle the [lat, lon] fields.

You also want it to save coordinate and unit/long_name metadata if possible (which makes me realize the video file doesn't have metadata, created ai2cm/ace#209).

**Comment by oliverwm1** [comment]
+1 to averaging over initial condition and time (same as what is being done for the maps reported in wandb).

**Comment by brianhenn** [comment]
Agree with all of the above, including just storing the average over initial condition.

I just also wanted to support deleting (or updating for this task if helpful) the `time_mean.get_dataset` method as part of this task. I didn't understand its purpose since it isn't called at all, so it probably no longer really functions as intended once I added the lat/lon images in what's returned by `get_logs`. I probably should have looked into deleting it then.

**Comment by gideonite** [comment]
I'm looking at using the `get_dataset` function now. This is actually close to what we want. See this draft PR (#333). The problem is that `get_logs` is hard-coded to be for WandB whereas we want to use a different hook for `get_dataset`. My sense is just to add a level of abstraction by add a private `_get_image` function which factors out what is being done in `get_logs` (see below) and uses it in the get_dataset function as well.

```py
logs = {}
for name in self._gen_data.keys():
    gen = self._dist.reduce_mean(self._gen_data[name] / self._n_batches)
    target = self._dist.reduce_mean(self._target_data[name] / self._n_batches)
    images = {"bias_map": gen - target, "gen_map": gen}
    for key, data in images.items():
        # this should be generalized to be raw data which can be converted to wandb
        # format by `get_logs` or packed into an xarray dataset in `get_dataset`
        logs[f"{key}/{name}"] = self._get_image(key, name, data)
```

Any thoughts on this? @mcgibbon

**Comment by mcgibbon** [comment]
Please read the [VideoAggregator](https://github.com/ai2cm/full-model/blob/main/fme/fme/core/aggregator/inference/video.py#L415)'s `get_dataset` and the way it calls its helper `_get_data` for my thoughts on how to do this. Basically I would suggest making a new helper layer that returns raw data, and wrapping this in xarray datasets or wandb images as appropriate in the two methods `get_dataset` and `get_logs`.

**Comment by gideonite** [comment]
Do these outputs work for us? I'm making a separate file for each diagnostic type. @oliverwm1 

- The next step is to get the metadata (units and long name) in.
- I guess it would be nice to standardize the variable names as well and remove "inference" which is superfluous.

```
In [6]: xr.open_dataset("time_mean_diagnostics.nc")
Out[6]:
<xarray.Dataset>
Dimensions:                 (dim_0: 1, dim_1: 16, dim_2: 32)
Dimensions without coordinates: dim_0, dim_1, dim_2
Data variables:
    inference-bias_map-foo  (dim_0, dim_1, dim_2) float32 ...
    inference-rmse-foo      float64 ...
    inference-bias-foo      float64 ...
    inference-gen_map-foo   (dim_0, dim_1, dim_2) float32 ...
    inference-bias_map-bar  (dim_0, dim_1, dim_2) float32 ...
    inference-rmse-bar      float64 ...
    inference-bias-bar      float64 ...
    inference-gen_map-bar   (dim_0, dim_1, dim_2) float32 ...

In [7]:  xr.open_dataset("mean_norm_diagnostics.nc")
Out[7]:
<xarray.Dataset>
Dimensions:                                       (forecast_step: 7)
Coordinates:
  * forecast_step                                 (forecast_step) int64 0 ... 6
Data variables:
    inference_weighted_bias-bar                   (forecast_step) float64 ...
    inference_weighted_bias-foo                   (forecast_step) float64 ...
    inference_weighted_grad_mag_percent_diff-bar  (forecast_step) float64 ...
    inference_weighted_grad_mag_percent_diff-foo  (forecast_step) float64 ...
    inference_weighted_mean_gen-bar               (forecast_step) float64 ...
    inference_weighted_mean_gen-foo               (forecast_step) float64 ...
    inference_weighted_rmse-bar                   (forecast_step) float64 ...
    inference_weighted_rmse-foo                   (forecast_step) float64 ...
In [9]: xr.open_dataset("zonal_mean_diagnostics.nc")
Out[9]:
<xarray.Dataset>
Dimensions:              (dim_0: 16, dim_1: 7)
Dimensions without coordinates: dim_0, dim_1
Data variables:
    inference-gen-foo    (dim_0, dim_1) float32 ...
    inference-error-foo  (dim_0, dim_1) float32 ...
    inference-gen-bar    (dim_0, dim_1) float32 ...
    inference-error-bar  (dim_0, dim_1) float32 ...
```

**Comment by oliverwm1** [comment]
```In [6]: xr.open_dataset("time_mean_diagnostics.nc")
Out[6]:
<xarray.Dataset>
Dimensions:                 (dim_0: 1, dim_1: 16, dim_2: 32)
Dimensions without coordinates: dim_0, dim_1, dim_2
Data variables:
    inference-bias_map-foo  (dim_0, dim_1, dim_2) float32 ...
    inference-rmse-foo      float64 ...
    inference-bias-foo      float64 ...
    inference-gen_map-foo   (dim_0, dim_1, dim_2) float32 ...
    inference-bias_map-bar  (dim_0, dim_1, dim_2) float32 ...
    inference-rmse-bar      float64 ...
    inference-bias-bar      float64 ...
    inference-gen_map-bar   (dim_0, dim_1, dim_2) float32 ...
```
Agreed to removing "inference". Also need useful dimension names and corresponding coordinates (e.g. lat/lon coords). See the "raw" dataset netCDF writer for what we use there, should make sure we use the same conventions.

```
In [7]:  xr.open_dataset("mean_norm_diagnostics.nc")
Out[7]:
<xarray.Dataset>
Dimensions:                                       (forecast_step: 7)
Coordinates:
  * forecast_step                                 (forecast_step) int64 0 ... 6
Data variables:
    inference_weighted_bias-bar                   (forecast_step) float64 ...
    inference_weighted_bias-foo                   (forecast_step) float64 ...
    inference_weighted_grad_mag_percent_diff-bar  (forecast_step) float64 ...
    inference_weighted_grad_mag_percent_diff-foo  (forecast_step) float64 ...
    inference_weighted_mean_gen-bar               (forecast_step) float64 ...
    inference_weighted_mean_gen-foo               (forecast_step) float64 ...
    inference_weighted_rmse-bar                   (forecast_step) float64 ...
    inference_weighted_rmse-foo                   (forecast_step) float64 ...
```
I'm not sure we really need to save out these diagnostics since they are already available from the wandb API. Also note we use "timestep" dim name elsewhere.
```
In [9]: xr.open_dataset("zonal_mean_diagnostics.nc")
Out[9]:
<xarray.Dataset>
Dimensions:              (dim_0: 16, dim_1: 7)
Dimensions without coordinates: dim_0, dim_1
Data variables:
    inference-gen-foo    (dim_0, dim_1) float32 ...
    inference-error-foo  (dim_0, dim_1) float32 ...
    inference-gen-bar    (dim_0, dim_1) float32 ...
    inference-error-bar  (dim_0, dim_1) float32 ...
```
Similar comments as for the "time_mean_diagnostics" above.
