### ISSUE TITLE
specific_total_water_0 plots are often black in wandb

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#196]
I've been finding a lot of the time plots pertaining to specific_total_water_0 appear plain black, for example [here](https://wandb.ai/ai2cm/fourcastnet/reports/inference-time_mean-bias_map-specific_total_water_0-23-08-21-12-45-00---Vmlldzo1MTk1MzU4). I'd expect to at least see one white pixel at the max colorbar bound.

No idea what's causing this.

**Comment by brianhenn** [comment]
Yeah, this is odd. Similar behavior seen in other variables generated by other aggregators with different scale numbers: [example](https://wandb.ai/ai2cm/fourcastnet/reports/val-snapshot-image-full-field-PRESsfc-23-08-21-11-50-34---Vmlldzo1MTk2MDU5)

**Comment by mcgibbon** [comment]
I tracked down the [wandb code that does this conversion](https://github.com/wandb/wandb/blob/main/wandb/sdk/data_types/image.py#L269), and yeah, it wouldn't work for wildly scaled data. Numpy arrays get cast to unsigned 8-bit integer (uint8), which won't be able to hold wildly-scaled data.

I've opened an [upstream issue](https://github.com/wandb/wandb/issues/6287), but we should fix it on our end in the meantime.
