### ISSUE TITLE
NaN is appearing in video data

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#199]
As discussed ([comment](https://github.com/ai2cm/full-model/pull/289/files#r1302128162)) and worked around in ai2cm/full-model#289, NaN is appearing in video data requiring the use of nanmin and nanmax. Ideally we should figure out why this is happening and correct the root cause.

**Comment by oliverwm1** [comment]
I thought this issue was resolved?

I recently did an inference run that generated videos and did not see any NaNs: https://wandb.ai/ai2cm/fourcastnet/runs/hl08ymcz?workspace=user-oliverwm

**Comment by mcgibbon** [comment]
I think this is resolved.
