### ISSUE TITLE
Optimization class has separate concerns from Stepper

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#201]
Currently the Stepper owns the Optimization object, even though inference (which depends on Stepper) does not make any use of optimization. This results extra type-checking and value-checking logic, such as the `load_optimizer: bool` flag on SingleModuleStepper's loading routines, and a check that there's an optimizer if `train=True` is passed to `run_on_batch`.

This was done in part because some `run_on_batch` routines might require multiple optimizers or have other requirements for optimization, but this can be handled in a similar way to DataRequirements if we need to do this down the line, and it's not a concern currently.

To fix this, we should pull the Optimization object up one level and pass it in as an argument to `run_on_batch`, similarly to how we pass in an aggregator.

Changes include:
- SingleModuleStepperConfig.optimization is moved to TrainConfig.optimization.
- The `train: bool` argument is removed from `SingleModuleStepepr.run_on_batch`, and is replaced with an optional argument `optimization: Union[optimization, NullOptimization] = NullOptimization()`.
- Optimization is passed from `Trainer.train_one_epoch` instead of `train=True`.
- "optimizer" key is added to `Trainer.save_checkpoint`'s saved artifact.
- Trainer.restore_checkpoint will directly restore the optimizer from `checkpoint["optimizer"]` if this key is present, or do nothing if it is not present
- All references to `self.optimization` are removed from SingleModuleStepper, including in the load_state/from_state routines.

Requirements include:
- Inference should be able to load checkpoints saved before this refactor was made.

**Comment by oliverwm1** [comment]
Having the optimization outside of the stepper makes sense to me. I’m a bit wary of breaking changes at this time. In particular it would be helpful to be continue to be able to load existing checkpoints and doing inference with them (and ideally further training, although I suspect that may be more challenging). How feasible is this?

**Comment by gideonite** [comment]
> I’m a bit wary of breaking changes at this time. 

+1

**Comment by mcgibbon** [comment]
> Having the optimization outside of the stepper makes sense to me. I’m a bit wary of breaking changes at this time. In particular it would be helpful to be continue to be able to load existing checkpoints and doing inference with them (and ideally further training, although I suspect that may be more challenging). How feasible is this?

This change should be backwards-compatible for inference, since inference doesn't load the optimizer anyways. I'll update the issue. I'm not planning to make it backwards-compatible for training because we don't have fine-tuning yet anyways, so backwards-compatibility shouldn't be an issue.

**Comment by gideonite** [comment]
This is considered the first step towards building a fine-tuning system.

**Comment by gideonite** [comment]
I've taken a stab at this in ai2cm/full-model#318. This PR is not complete yet, but it would be great to confirm that this is what were expecting to get done here. @mcgibbon

**Comment by gideonite** [comment]
Why do we need to change the signature of `run_on_batch`? What if we just passed optimization config as an argument. This would require fewer code changes. There's also the tricky issue that optimization cannot be initialized without an initialized stepper. Thus stepper needs to be passed to optimization to create. @mcgibbon

**Comment by mcgibbon** [comment]
The `optimization` object should be removed from the stepper:
> Currently the Stepper owns the Optimization object, even though inference (which depends on Stepper) does not make any use of optimization. This results extra type-checking and value-checking logic, such as the load_optimizer: bool flag on SingleModuleStepper's loading routines, and a check that there's an optimizer if train=True is passed to run_on_batch.
