### ISSUE TITLE
Hard code batch size = num GPU

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#202]
In my experience, we almost always want the batch size to equal the number of available GPUs. Unfortunately, this requires changes to two config files in vcm-control-workflow which I often overlook. I would propose the following changes:

```py
batch_size: Optional[int]
```

and 
```py
if batch_size is None:
   # set batch size to the number of parallel workers by default
   batch_size = dist.world_size
```
in `__post_init__`. See [data_loading/params.py](https://github.com/ai2cm/full-model/blob/d11c185a1a9d9bd470b496499659c4c2d482a0d1/fme/fme/core/data_loading/params.py#L44).

**Comment by oliverwm1** [comment]
I have definitely trained quite a few models with batch size greater than # of GPUs, although I agree that has generally been the less common case.

Batch size is an important parameter so I'm somewhat hesitant about adding a default for it, but I agree that the default of "world size" is a reasonable one.

**Comment by gideonite** [comment]
Interesting -- sounds like we aren't decided yet so this issue may be a
useful place for further discussion. Leaving open for now.

For what it's worth, I envision a `batch_size` parameter commented out in
the config code so that it's clear how to use it but the naive experimenter
doesn't have to worry about their jobs running out of memory if they run
with the default settings.

**Comment by mcgibbon** [comment]
I find I'm usually training on 1 GPU (to test more configurations) with a batch size of 4 to match what Oli is using.

I was also going to say batch size has a pretty significant effect on training, so I'd be hesitant to add a default for it. I'd want to make sure that when someone changes the number of GPUs they're running on, they realize they're changing the size of a gradient update batch.

**Comment by gideonite** [comment]
> I find I'm usually training on 1 GPU (to test more configurations) with a batch size of 4 to match what Oli is using.

I'm surprised that this even runs with OOM errors. My reasoning for doing this is that it seems like the GPU memory maxes out at one training example.

**Comment by mcgibbon** [comment]
It might have worked for me because I was using a configuration with half as many blocks, I don't know.

**Comment by gideonite** [comment]
No longer relevant
