### ISSUE TITLE
GPU test unreliable because of unavailability of GPUs

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#213]
We currently run our unit tests on 2 GPUs via this github action:

https://github.com/ai2cm/full-model/blob/dc36c2a0a7379965453b1c572f6be7dfa4767d4d/.github/workflows/fme-unit-tests.yaml#L34

However this test sometimes doesn't run or even times out. It seems this is due to google not having available GPUs (see discussion https://allenai.slack.com/archives/C052FC4NU0G/p1694450503984529).

I suggest we make this action not required for merging PRs, so that people are not blocked if this action doesn't run because of GPU unavailability. Of course if the tests run and fail, they should be fixed before merging.

**Comment by gideonite** [comment]
Wow, I've had a [PR ready](https://github.com/ai2cm/full-model/pull/333) for testing overnight and the GPU test still hasn't been scheduled. Maybe we should require a beaker job link that shows that the code runs on beaker as a sanity check. We can add that to the PR template?

**Comment by oliverwm1** [comment]
I would be hesitant to add testing-on-beaker as a requirement since that requires manual intervention and would slow down PR process.

@frodre any ideas of how to make this test more reliable? Is there any way to know if certain regions generally have more GPU availability, or to have the cluster that this is running on be able to spin up workers in multiple regions?

**Comment by frodre** [comment]
After looking over our current terraform tooling, I don't think it will be too difficult to spin up a "regional" cluster that can at least source GPUs from all the us-central1 zones.  More than that would likely take some more effort.

**Comment by mcgibbon** [comment]
Is it possible to keep one of the GPU test workers always running, even when no tests are ongoing? Especially if we can do this only during the workday?

**Comment by frodre** [comment]
It could be technically possible, but probably complicated.  Once the update PR gets merged we can see if we run into large testing delays on spinup for regional GPU sourcing.

**Comment by oliverwm1** [comment]
Going to close this given @frodre's update in ai2cm/full-model#352. If issue arises again we can reopen.
