### ISSUE TITLE
Specify units for generated data.

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#214]
A bit confused why we wouldn't have units available for generated data. This originally came up in the discussion (linked below).

_Originally posted by @oliverwm1 in https://github.com/ai2cm/full-model/pull/333#discussion_r1333717946_

**Comment by oliverwm1** [comment]
I'm not sure what is meant by "generated data" here.

**Comment by oliverwm1** [comment]
I'm closing this issue because it's not clear what diagnostic/metric/log is being referred to. If we have a more specific case of missing metadata, can make a new issue.
