### ISSUE TITLE
inference: zonal mean image flip

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#218]
It looks like ai2cm/full-model#333 reversed the dimension order of the zonal-mean images (from x: time, y: lat to x:lat, y:time). See that in wandb output with test toy data from the commits [before](https://wandb.ai/ai2cm/fme/runs/49kvoaqg) and [after](https://wandb.ai/ai2cm/fme/runs/jia0lq42) the PR, the zonal-mean images flipped dimensions. From looking quickly at the PR I don't see why that happened, but we should bring time-on-the-x back because it makes it easier to look at zonal-mean images for longer runs. 

@gideonite

**Comment by gideonite** [comment]
This bug should be fixed in ai2cm/full-model#367 which I've taken the liberty of assigning to you. Thanks for carefully isolating this error! @brianhenn
