### ISSUE TITLE
Retrieve TIMESTEP_SECONDS from dataset

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#227]
Budget corrections require knowing the timestep. We should add logic to retrieve this from the dataset.

**Comment by oliverwm1** [comment]
Note that we already retrieve a time coordinate from the dataset, so this should be reasonably straightforward.

e.g.

https://github.com/ai2cm/full-model/blob/6683a005ef15873347cbccc66fcf6f83ca3e9302/fme/fme/core/data_loading/_xarray.py#L259
