### ISSUE TITLE
Add metric for "time-mean RMSE" averaged across channels

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#231]
Would be useful to have a single number for time-mean inference skill. We'll need to use the normalized channels for an average across channels to be useful. This will mean the resulting value will not have units and not be comparable across different normalization strategies, but still would be useful, e.g. for hyperparameter experiments.

**Comment by mcgibbon** [comment]
Because this output will be used for ai2cm/ace#102, the inference_one_epoch routine will need to be able to return this value to the level above it where we save checkpoints.
