### ISSUE TITLE
Time-aggregated inference metrics and/or raw predictions 

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#232]
We're getting to the point of wanting more control over ACE inference output than what we can easily see in WandB from every-timestep global-mean series and time-mean maps. For example, for AMIP data we might want to compute global-mean trends and time-varying indices, which is klunky to do with 4e4 6-hourly json-logged values in WandB for a 30-year run. We can output full-dimension variables via the raw prediction netcdf, but a single 1deg variable is about 20GB at 6-hourly resolution over 30 years.

So some time aggregation done within the inference routine would be useful. This could be added to WandB-logged metrics, to a raw predictions netcdf, or both. Since we have the time coordinates of the data as xarray objects already, it shouldn't be too hard to use those to maintain running tallies over a specified aggregation period, e.g. monthly. The aggregation period could be configurable maybe.

**Comment by mcgibbon** [comment]
Writing period-mean values sounds good. Might be tricky to get monthly values since the length of a month is inconsistent.

**Comment by oliverwm1** [comment]
Monthly means would be relatively straightforward if an inference run has a single initial condition. Monthly averages are typically computed by averaging all time steps that fall within a particular calendar month, so the differing lengths of months is not an issue. However, if a run has multiple initial conditions with different start times, it is not necessarily possible to use the "(start_time, lead_time)" coordinate we currently use for raw netCDF output. We could require that jobs which request monthly averaging of outputs can only have a single initial condition.

**Comment by brianhenn** [comment]
Sounds good. It sounds like we want to apply this to the raw output (not wandb metrics). And yeah will have to think about the multi-sample different init times case.

**Comment by mcgibbon** [comment]
> We could require that jobs which request monthly averaging of outputs can only have a single initial condition.

This may not be required. I think the typical way to convert xarray data into monthly is to create a variable which indicates how many months into the simulation, and then groupby/reduce based on that variable. This should work just fine if the "months elapsed" variable is computed from the `init_time + time_elapsed` variable. We could also store a 1D variable across samples indicating the `init_month`, to be able to create an annual cycle average across initializations.

Not sure if we care about the first/last month of a run having fewer samples going into a mean, which could happen with any of these.

**Comment by oliverwm1** [comment]
> It sounds like we want to apply this to the raw output (not wandb metrics)

Honestly both would be useful, but probably good to scope this to just one or the other to start (and raw output may be better starting place, since it can have a richer time coordinate).

> I think the typical way to convert xarray data into monthly is to create a variable which indicates how many months into the simulation, and then groupby/reduce based on that variable.

I think the groupby is typically done on the calendar month, not on a "months since start" variable. E.g. if you configure FV3GFS to output monthly means and start it on Feb 15, it would return the Feb 15-28 average, then the March 1-31 average, etc. @spencerkclark is this right? (This is also true when using xarray/pandas, where you would typically do a groupby on the calendar month). But yes, it is true different # of samples would go into each month. We could output a bounds variable which indicates the averaging boundaries, but this may be overkill.

**Comment by mcgibbon** [comment]
The way I was thinking about it you are correct @oliverwm1 . When I said "months elapsed" I only mean that e.g. months in the second year are 12-23, and that the first `months_elapsed` (or `months_index`? just `months`?) is 0 regardless of calendar month. We could recover calendar month by `initial_month + months_elapsed`. But yes the month starts on its 1st date, not on the initialization date.

**Comment by spencerkclark** [comment]
> E.g. if you configure FV3GFS to output monthly means and start it on Feb 15, it would return the Feb 15-28 average, then the March 1-31 average, etc. @spencerkclark is this right?

Sorry, I had to run a few tests to verify this, but to output monthly mean diagnostics with FV3GFS you need to initialize on the first of a month, and run in segments that are an even multiple of months.  Partial monthly means are not supported (I'm not sure that's necessarily relevant here, however).

It's probably fine to just fill with NaN, but I'll point out that for equal-duration runs, some might require a longer `months_elapsed` dimension than others depending on the date of the initial condition.
