### ISSUE TITLE
Inference is slower than we'd like, and depends strongly on storage quality

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#237]
We've noticed a wide spread in inference performance depending on filesystem/storage and in general would like to have inference be as performant as possible in order to not slow down iteration cycle. Especially as we move towards regularly analyzing multi-decade long runs.

To me the following items are potential low-hanging fruit:
1. Stop initializing new data loaders for each "window" of data, since this initialization is often slow. I think this could be achieved by restricting inference to run only a single batch of initial conditions (would also simplify inference code). See ai2cm/ace#255 
2. Log to wandb during inference, instead of after. Could avoid sleep calls. See ai2cm/ace#192, but note this is challenging for the case of multiple batches for inference.
3. Enable running inference without loading all target data for verification ai2cm/ace#258 

It may be worth also doing some more careful profiling of inference code.

**Comment by brianhenn** [comment]
Just curious why doing the wandb logging during inference is challenging for the case of multiple batches? Seems like we could wait until the inner loop over batches completes, then log the averaged results across batches for that window.

**Comment by oliverwm1** [comment]
> Just curious why doing the wandb logging during inference is challenging for the case of multiple batches? Seems like we could wait until the inner loop over batches completes, then log the averaged results across batches for that window.

@brianhenn We could log to wandb at end of each window, which would help with getting feedback on run performance sooner versus logging the entire timeseries at the end of the run. But it would still require the `sleep` calls to avoid overloading wandb API. If we only have a single batch, then we can log to wandb after each time step and avoid any sleep calls, because each time step takes long enough that we won't ping wandb too much. This way the upload would happen simultaneously as the run proceeds.
