### ISSUE TITLE
Potentially unnecessary float cast is duplicated

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#245]
In ai2cm/full-model#440, we identified that a cast to float is duplicated between [fme/fme/fcn_training/inference/loop.py](https://github.com/ai2cm/full-model/pull/440/files/9f2db7ccfd2825f4b06648f2988c3ca6bddde524#diff-bf27e0d31ce3097128e8e9df86c612a0da26ce0c14dc7b37b65d19c22c55c767) and the stepper run_on_batch routine. This cast may or may not be necessary - it was originally added to avoid dtyping issues within the SFNO calls.

We should check if the code and tests run without error without this cast (removing it if so), and/or update the code so this code is called in a helper instead of duplicated.

**Comment by AnnaKwa** [comment]
Attempted to just remove the higher level cast in PR 540- the GPU tests fail when it's removed.

**Comment by mcgibbon** [comment]
OK, in that case we should refactor the code to call a helper.
