### ISSUE TITLE
Update python and torch versions

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#246]
Currently we use python 3.8, mostly because the NVIDIA docker image that we base off of uses this python version. We could update to base off of a more recent NVIDIA docker image that uses python 3.10 and torch 2.1, and also update the corresponding versions that get installed in our conda env.

I started on this in ai2cm/full-model#396 but put it off because we were in the middle of open sourcing a version of the code. Now would be a good time to revisit. There were some difficulties in getting apex to install in an environment without an NVIDIA GPU. Maybe we should just vendorize the portion of apex code required, or trying using the "FusedAdam" optimizer from pytorch instead of from apex.

**Comment by gideonite** [comment]
Excited to get this through because I think it'll help with get an automated diagram of the model that we are using.

> or trying using the "FusedAdam" optimizer from pytorch instead of from apex.

This seems like the best idea to me but would require some testing to make sure that we aren't inadvertently breaking or slowing down things.

**Comment by oliverwm1** [comment]
> This seems like the best idea to me but would require some testing to make sure that we aren't inadvertently breaking or slowing down things.

I agree. I just launched a 'production' config training job that uses the pytorch optimizer, so we'll see how it works.
