### ISSUE TITLE
Inference: histogram can hang indefinitely on tensor with uniform values

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#248]
Calling `HistogramDataWriter.append_batch` with a target or prediction variable tensor that is uniform across lat/lon/sample on its first call will cause it to hang indefinitely upon subsequent calls of `HistogramDataWriter.append_batch` that are not uniform. It's because the `DynamicHistogram` uses the difference between the tensor's smallest and largest values to set the initial range for iteratively doubling the histogram bin range when values outside that range are seen. If the initial range is zero, it can never double its way to including the new values, [see code](https://github.com/ai2cm/full-model/blob/cac75610707a853d0aecbf015668a8f4226eefde/fme/fme/core/histogram.py#L31-L91). If we want to keep the current iterative bin range doubling, we could require that the calculated range not be less than a small positive value so that at least it can't get stuck.

**Comment by oliverwm1** [comment]
This was resolved by ai2cm/full-model#446
