### ISSUE TITLE
Inference behavior depends on `forward_steps_in_memory` parameter

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#249]
The `forward_steps_in_memory` parameter exists to enable splitting inference into multiple segments in order to not require keeping the entire timeseries in memory at once. Changing this parameter should not change the evolution of an inference simulation. However we are finding that this is the case.

For example, compare these two runs which used the same model and forcing data. One used a `forward_steps_in_memory=200` ([link](https://wandb.ai/ai2cm/fourcastnet/runs/hl08ymcz?workspace=user-oliverwm)) and the other used `forward_steps_in_memory=365` ([link](https://wandb.ai/ai2cm/fourcastnet/runs/j392it9k?workspace=user-oliverwm)). Their evolution starts to diverge at step 201, i.e. right at the start of the second window.

Plot of instantaneous surface pressure RMSE as function of step.

Step 200 highlighted:
![Screen Shot 2024-01-03 at 4 42 45 PM](https://github.com/ai2cm/ace/assets/23640870/9b05ad71-026e-49b2-9447-65cc5334bbd6)

Step 201 highlighted:
![Screen Shot 2024-01-03 at 4 42 57 PM](https://github.com/ai2cm/ace/assets/23640870/89d5c920-aea8-412c-822e-8b6a8dfd0559)

**Comment by mcgibbon** [comment]
I remember writing a unit test that asserts this isn't the case, but it may only happen if we use the SFNO code instead of some simple testing model.

**Comment by brianhenn** [comment]
Closing the loop here, this was caused by the extra norm/denorm outside of the autoregressive timestepping inside `run_on_batch`. The refactor in ai2cm/full-model#603 will resolve it.
