### ISSUE TITLE
Automated model diagram

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#251]
Now that ai2cm/ace#246 has been merged, it would be great to have an automated way to visualize our latest model(s).

**Comment by gideonite** [comment]
This is done. https://github.com/ai2cm/full-model/tree/gideon/module-diagram. The resulting diagram (exported below as png) is moderately useful. Note that this required some hacks to get it to work due to issues with onnx not knowing how to handle fft. 

![sfno-onnx-export](https://github.com/ai2cm/ace/assets/2163686/e0b18568-5c3e-4d57-8d1b-9c46d6020c6e)

**Comment by mcgibbon** [comment]
Really great! Is the code to generate this something we can merge into the repo? If it requires some environment hacks, can we put it in a project folder with its own environment setup instructions?

**Comment by gideonite** [comment]
Cool, glad to hear that it's generating some excitement. Yes, There are a few hacks but nothing that I don't think can't be automated. I'll submit a PR for this sometime this week.

**Comment by gideonite** [comment]
I don't think there's enough excitement about this to warrant maintaining the script. I've tried to update it but run into some novel problems which are probably coming up due to recent code changes. I'll leave the branch up in case we ever want to follow up with this. [gideon/module-diagram](https://github.com/ai2cm/full-model/tree/gideon/module-diagram)

**Comment by mcgibbon** [comment]
I would really prefer to have this kind of figure available for when we discuss model issues. It would have saved us a lot of time (and potential for human error) when we were tracing the model code to track how instance normalization works the other week.
