### ISSUE TITLE
Improve input/output tracking for perlmutter jobs

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#253]
Currently it's hard to find the output of perlmutter jobs. We discussed some ways we might improve this, such as automatically uploading the job logs as a wandb artifact so they are easily accessible.

It's also hard to determine what paths were mounted as input to perlmutter jobs.

**Comment by oliverwm1** [comment]
Related/duplicate: https://github.com/ai2cm/vcm-workflow-control/issues/194
