### ISSUE TITLE
Delete redundant or underutilized wandb metrics

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#254]
Having many wandb metrics makes our run pages harder to use. If possible, we should try to prune what we are computing in the aggregators and saving to wandb. I've identified some potential candidates below.

From the "training" page:
- remove `inference/mean_step_20/l1` since it is similar to `inference/mean_step_20/weighted_rmse`
- remove `val/mean/l1` since it is similar to `val/mean/weighted_rmse`

From the "inference" page:
- remove `inference/mean_norm/weighted_grad_mag_percent_diff` because it is identical to the denormalized version
- remove `inference/mean_step20/l1`

**Comment by gideonite** [comment]
Wondering whether this is as simple as what is done in https://github.com/ai2cm/full-model/pull/471
