### ISSUE TITLE
Save inference initial conditions separately

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#256]
During ai2cm/full-model#446 it became apparent that for an inference run saving the full data of the initial conditions separately from the rest of the timesteps' raw predictions would be beneficial (e.g., if we coarsen the predictions before saving, we presumably don't want to coarsen the initial conditions). A single-timestep IC dataset could be written out on the first inference window. This might also allow reducing some of the complexity in writing data since first windows would no longer be size +1 relative to the rest. We'd have to decide whether splitting the IC off from the rest of the data would happen just for the `PredictionDataWriter`, or also for the `VideoDataWriter` and `HistogramDataWriter`.

**Comment by mcgibbon** [comment]
> if we coarsen the predictions before saving, we presumably don't want to coarsen the initial conditions

I'm not so sure about that. The step 1 values will also be much more accurate than a typical value, but we don't throw them out. I think if we care about this kind of spin-up we wouldn't look at the initial data anyways.
