### ISSUE TITLE
Rename Dict[str, torch.Tensor] to TensorMapping across the codebase

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#261]
Cool, just move into `fme/core/typing_.py`. We might want to refactor but that's something that can be done later.

_Originally posted by @gideonite in https://github.com/ai2cm/full-model/issues/490#issuecomment-1908782393_

**Comment by gideonite** [comment]
I can imagine that we can even start added methods to this type to avoid a dict comprehension every time we want to do anything.

**Comment by oliverwm1** [comment]
Note there is an existing project that provides this kind of container and would make things like indexing in time much easier. It's still beta and not convinced we want to depend on it, but we should monitor and maybe take some inspiration: https://github.com/pytorch/tensordict

**Comment by gideonite** [comment]
While this may be beyond our scope, [pytrees](https://jax.readthedocs.io/en/latest/pytrees.html#extending-pytrees) are a super interesting abstraction from the jax community.
