### ISSUE TITLE
Some aspects of stepper are serialized in two places

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#263]
When we convert the stepper to a serializable format, some items are serialized in two places. Once as part of the overall stepper config, and then additionally as explicit items within the dict returned by `SingleModuleStepper.get_state`:

https://github.com/ai2cm/full-model/blob/8ba38ef86bf5024f7b5e0a98f7381c3873cc2e3d/fme/fme/core/stepper.py#L297-L312

Specifically, `in_packer`, `out_packer` and `prescriber` are all completely defined by their config (they don't have any 'state' beyond this) and so are already fully described by the `config: self._config.get_state()` item. Note we already rely on the top-level stepper config to serialize other aspects of the stepper like the "corrector" config.

**Comment by oliverwm1** [comment]
@mcgibbon would you be good with me cleaning this up a bit? (i.e. remove in_packer, out_packer, prescriber from this dict). I got a bit confused when adding the slab ocean to the stepper, and I think part of my confusion stemmed from this issue.

**Comment by mcgibbon** [comment]
Sounds good to me.
