### ISSUE TITLE
Use coarse/fine instead of lowres/highres

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#269]
In terms of naming... in our group we (at least try) to use "coarse" and "fine" instead of "low-res" and "high-res". This can avoid some ambiguity that arises from, for example, say some resolution is "larger" than another one. I would consider following that nomenclature.

_Originally posted by @oliverwm1 in https://github.com/ai2cm/full-model/pull/507#discussion_r1476802159_

**Comment by mcgibbon** [comment]
This comes up frequently in review and should be a rubber-stamp review process if all the PR is doing is this rename.
