### ISSUE TITLE
Use DataRequirements instead of naked values

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#273]
Wrap data_vars in DataRequirements. 

              Because this PR is so minor I won't block it, but `DataRequirements` as a concept is supposed to be the thing encapsulating everything the model config needs to tell the data loader about the data. The argument should be `requirements` and this should be constructed by your model config.

_Originally posted by @mcgibbon in https://github.com/ai2cm/full-model/pull/528#discussion_r1482092375_

**Comment by mcgibbon** [comment]
This is something that can bite us with time if we extend the code, and I think should get done even though it's more than a single-operation change. This should be very fast to fix, but will be slower if we don't have the same idea of what this change means and have to go back and forth in review. I'd suggest that I should make a PR fixing this and you can review it, unless you're sure we're on the same page.
