### ISSUE TITLE
Turn TensorMapping into a dataclass with useful helper methods

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#275]
It's starting to come up that common operations boil down to writing the same dict comprehension again and again.

              I don't see any reason why these shouldn't be methods on a TensorMapping data class in core.

_Originally posted by @gideonite in https://github.com/ai2cm/full-model/pull/529#discussion_r1484466155_

**Comment by oliverwm1** [comment]
We've settled on having a higher level `BatchData` as a dataclass with these sorts of helper methods, so I am going to close this.
