### ISSUE TITLE
XarrayDataset requires full DataLoaderParams object

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#276]
Our data loader config has a `dataset: XarrayDataParams` item. We should ensure that the `XarrayDataset` object only requires this part of the data loader config. Currently the `XarrayDataset` takes the full `DataLoaderParams` because it requires `n_samples` and `window_starts` items.

https://github.com/ai2cm/full-model/blob/d8469644bf3baa33d6a1ed63e28260e7eac4831f/fme/fme/core/data_loading/params.py#L41-L61

**Comment by oliverwm1** [comment]
I think we should delete all the code related to the `window_starts` option, since we no longer use this for inference. The inference dataset/loader has its own configuration for determining what initial conditions to use.

The `n_samples` option should not be used by `XarrayDataset`, instead we should use `torch.utils.data.Subset`: https://pytorch.org/docs/stable/data.html#torch.utils.data.Subset after the `XarrayDataset` has already been created.

**Comment by mcgibbon** [comment]
I'm not sure exactly what form this will take, but I think basically our current XarrayDataset needs to be separated into a base class that lets us access xarray data split between multiple netCDFs (and is re-used by the inference data loading), and a true torch.Dataset class that wraps over top of it to provide training data sampling. Then the config for the torch.Dataset can include all the additional sampling options, and we can re-use just the base configuration (corresponding to what is currently the "xarray dataset" config, but isn't really).
