### ISSUE TITLE
Rename InferenceAggregator to Aggregator 

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#277]
> Also, nit: Why are both the train and validation ones' type name "inference"? If the idea is that there is just one aggregator that performs evaluations of predictions in a generic context, maybe just Aggregator would be most informative.

Also, nit: Why are both the train and validation ones' type name "inference"? If the idea is that there is just one aggregator that performs evaluations of predictions in a generic context, maybe just `Aggregator` would be most informative.

_Originally posted by @brianhenn in https://github.com/ai2cm/full-model/pull/529#discussion_r1484750038_

**Comment by mcgibbon** [comment]
This has come up in a few reviews and is a straightforward VS code refactor operation, I think we should just get it over with.

**Comment by gideonite** [comment]
Fixed in ai2cm/full-model#529
