### ISSUE TITLE
s/L1Loss/L1/

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#283]
nit (for another PR if at all): it's a bit of a stutter to say the loss type is something with "loss" inside it, if you could make this e.g. "L1" to match the core options like "MSE" that would be better. You could also probably use the class in core if you add L1 to it.

_Originally posted by @mcgibbon in https://github.com/ai2cm/full-model/pull/529#discussion_r1488073326_

**Comment by mcgibbon** [comment]
Probably the better solution for this is using `core`'s loss configuration object and adding L1 support to it, which is a small and focused PR but not trivial.
