### ISSUE TITLE
Use loaders consistently for metadata

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#284]
Nit: Probably won't matter but is there a reason to use the train loader for weights and the val loader for lats?

_Originally posted by @brianhenn in https://github.com/ai2cm/full-model/pull/529#discussion_r1488519401_

**Comment by mcgibbon** [comment]
This is a simple one-line change:
```
        self.latitudes = self.validation_loader.horizontal_coordinates.highres.lat.cpu()
```
becomes
```
        self.latitudes = self.train_loader.horizontal_coordinates.highres.lat.cpu()
```
