### ISSUE TITLE
Move initial validation metrics around 

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#285]
Nit: The intent (I think) of this and its logging might be clearer if the extra `valid_one_epoch` happened before the loop over epochs and the order of valid/train within the loop was reversed.

_Originally posted by @brianhenn in https://github.com/ai2cm/full-model/pull/529#discussion_r1488520481_

**Comment by mcgibbon** [comment]
This is a simple 3-line change:
```
        for epoch in range(self.num_epochs):
            logging.info(f"Epoch: {epoch+1}")
            self.valid_one_epoch()
            self.train_one_epoch()

        self.valid_one_epoch()
```
becomes
```
        self.valid_one_epoch()
        for epoch in range(self.num_epochs):
            logging.info(f"Epoch: {epoch+1}")
            self.train_one_epoch()
            self.valid_one_epoch()
```
