### ISSUE TITLE
rename in_names and out_names to coarse_names and fine_names

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#289]
in_names and out_names is not particularly descriptive for downscaling.

**Comment by oliverwm1** [comment]
On the other hand, you may have inputs which are fine resolution. For example, the fine-resolution topography which is a common input to use for downscaling.

**Comment by mcgibbon** [comment]
I think this shouldn't be renamed. It's important that the names convey the intent, and it's more important that these are the inputs and outputs of your ML model than that they're coarse or fine variables. Oli pointing out you can have fine inputs is an example of that. Also, this would add another name/concept to remember, and you'd have to remember whether the name is coarse vs lowres vs coarsened vs downscaled etc.

**Comment by gideonite** [comment]
>  For example, the fine-resolution topography which is a common input to use for downscaling.

This will likely be even more complex since there will be different types of inputs. E.g. some inputs which are fed as coarse variables, and some which are fed in as fine variables. This will require modifications for the model architecture and will vary per ML model implementation.

If anything, this further supports that in_names and out_names does not suit downscaling and that we need (a) different abstraction(s). @oliverwm1 @mcgibbon

**Comment by oliverwm1** [comment]
I'm not following. I agree there may be different types of inputs, but they are all inputs, so why is "in_names" not an appropriate name?

**Comment by gideonite** [comment]
Oli and I just had a quick 1:1 about this and it's clear that fine and coarse inputs need to be distinguished. Or, at least for some inputs, like topography. There's a question of how general we need to make this, e.g. should we just hard code topography as this special case and keep in_names out_names as is.
