### ISSUE TITLE
Re-factor count_parameters 

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#291]
> Suggestion (optional): This is OK, but there is a generic version of this you could write for all Models because they provide a `modules: torch.nn.ModuleList` attribute. You can iterate over those modules and count their parameters. In core, this is implemented as a `count_parameters(module_list: torch.nn.ModuleList)` helper function in train.py, called as `count_parameters(self.stepper.modules)`.
This way of writing it also makes it simpler to test, as you don't have to construct an entire Model class.

_Originally posted by @mcgibbon in https://github.com/ai2cm/full-model/pull/569#discussion_r1492652348_

Currently the `count_parameters` function is a method of Trainer, but it could just as easily be top-level. We could then re-use this function between many projects, e.g. including downscaling.

**Comment by mcgibbon** [comment]
Sounds good to me. It's also a very simple function, it would be OK to duplicate it.
