### ISSUE TITLE
Standalone inference data loader is called "validation_loader"

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#292]
Suggestion: rename it to "inference_loader". This would be a breaking change but with the effort we've made to optimize the inference loader as separate from the validation loader, it now seems odd that we [call the standalone inference data loader a "validation_loader"](https://github.com/ai2cm/full-model/blob/2a3397022d196b16786bce91846e5a0b9023ad48/fme/fme/fcn_training/inference/inference.py#L80). The inline inference loader is not referred to this way.

**Comment by oliverwm1** [comment]
Duplicate of ai2cm/ace#259?

I would just rename to "loader" since the "inference" part is implied due to being part of standalone inference config.

**Comment by brianhenn** [comment]
Yep duplicate thanks for catching

**Comment by brianhenn** [comment]
Duplicated by ai2cm/ace#259
