### ISSUE TITLE
Inference: Lack a monthly coarsening approach that's both fast and correct

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#299]
For inference we have a monthly coarsening implementation, but it's currently quite slow (see [wandb report](https://wandb.ai/ai2cm/fourcastnet/reports/Inference-writing-speed--Vmlldzo2OTgwNzA2)). We have a faster implementation of integer timestep coarsening but it can't by nature produce typical monthly mean values that we'd like. 

It would be much easier to do true monthly mean coarsening quickly once we implement ai2cm/ace-internal-test#243 .

**Comment by oliverwm1** [comment]
This was resolved by ai2cm/full-model#628
