### ISSUE TITLE
Add colorbar to images

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#302]
Currently color bars are missing from our snapshot and time mean maps and biases. It would be good to finally incorporate them.

**Comment by brianhenn** [comment]
Copying in a useful suggestion for how to do this from @mcgibbon on slack:

> What would we think of adding the "colorbar" to the right hand side of our wandb.Image plots by concatenating data value that scales linearly from the vmin to the vmax as it goes from lower right to upper right? This would be a lot like a true colorbar, except unlabelled. At least lets you estimate by eye what fraction of the colorbar range a certain color is at. One step past that is we could also place 20 equidistant 1-pixel-thick black markers along the right side (so it marks every 1/10th for a divergent colorbar) (or I guess 18, since the ends are markers).
We could implement this in the wandb.Image wrapper, so that it always gets applied (wouldn't apply to matplotlib figures as those don't use wandb.Image). (edited)

**Comment by mcgibbon** [comment]
If you want a baseline to improve on, I made a quick branch `feature/plot_colorbar` ([draft PR for changelog](https://github.com/ai2cm/full-model/pull/637/files)) which produces this test.png by straight data concatenation, with the "colorbar" width hard-coded to 10 pixels: 
![test](https://github.com/ai2cm/ace/assets/12307589/c20906c0-fbdf-48a2-afef-5420d77b2d5f)

FWIW it allowed for pretty fast iteration to call plt.savefig directly in that unit test. For matplotlib colorbars I'd suggest increasing the test data size to 4-degree (45 x 90).

**Comment by mcgibbon** [comment]
> Copying in a useful suggestion for how to do this from @mcgibbon on slack:
> 
> > What would we think of adding the "colorbar" to the right hand side of our wandb.Image plots by concatenating data value that scales linearly from the vmin to the vmax as it goes from lower right to upper right? This would be a lot like a true colorbar, except unlabelled. At least lets you estimate by eye what fraction of the colorbar range a certain color is at. One step past that is we could also place 20 equidistant 1-pixel-thick black markers along the right side (so it marks every 1/10th for a divergent colorbar) (or I guess 18, since the ends are markers).
> > We could implement this in the wandb.Image wrapper, so that it always gets applied (wouldn't apply to matplotlib figures as those don't use wandb.Image). (edited)

There was also an idea to do one better than this by using matplotlib colorbar in an intelligent way to get ticks and labels, while still keeping the image size the same.
