### ISSUE TITLE
Consolidate cast to device and dtype in stepper

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/ace#303]
Currently the tensor casting to device and float occurs in multiple spots in the stepper code (within MappingLoss, within stepper loop). ex. https://github.com/ai2cm/full-model/pull/641#discussion_r1524052211
We should figure out if we can do this at a single point outside the forward stepping.

**Comment by oliverwm1** [comment]
related: ai2cm/ace#300 

~~and possibly related: ai2cm/ace#249~~

**Comment by brianhenn** [comment]
On this note a couple points from debugging the inference determinism issue:
- [this cast](https://github.com/ai2cm/full-model/blob/96e824a4d3c75208c408ab1445c2c322697fd190/fme/fme/core/stepper.py#L319-L321) didn't appear to be affecting the device or dtype of the data on inference.
-  ai2cm/ace#249 didn't appear to be related to a device/dtype issue.
