### ISSUE TITLE
Job failed with "No numeric data to plot." during annual aggregator

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#308]
A recent job ([wandb link](https://wandb.ai/ai2cm/fourcastnet/runs/uxlpcadw/logs?nw=nwuseroliverwm)) failed during the "annual" inference aggregator step in inline inference. I'm guessing the reason is that the number of forward steps for inline inference was 1460 and so there was either only 1 or 0 years available. We should make sure the aggregator only is used when runs are long enough to have meaningful data.

Traceback:
```
58 Traceback (most recent call last):
59   File "/full-model/fme/fme/fcn_training/train.py", line 473, in <module>
60     main(yaml_config=args.yaml_config)
61   File "/full-model/fme/fme/fcn_training/train.py", line 464, in main
62     trainer.train()
63   File "/full-model/fme/fme/fcn_training/train.py", line 199, in train
64     inference_logs = self.inference_one_epoch()
65   File "/full-model/fme/fme/fcn_training/train.py", line 364, in inference_one_epoch
66     logs = aggregator.get_logs(label="inference")
67   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
68     return func(*args, **kwargs)
69   File "/full-model/fme/fme/core/aggregator/inference/main.py", line 161, in get_logs
70     logs.update(self._annual.get_logs(label="annual_weighted_mean"))
71   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
72     return func(*args, **kwargs)
73   File "/full-model/fme/fme/core/aggregator/inference/annual.py", line 179, in get_logs
74     gen[name].isel(sample=i_sample).plot(
75   File "/opt/conda/lib/python3.8/site-packages/xarray/plot/accessor.py", line 46, in __call__
76     return dataarray_plot.plot(self._da, **kwargs)
77   File "/opt/conda/lib/python3.8/site-packages/xarray/plot/dataarray_plot.py", line 285, in plot
78     raise TypeError("No numeric data to plot.")
79 TypeError: No numeric data to plot.
```

FYI @mcgibbon

**Comment by mcgibbon** [comment]
I'm kind of confused, because this is supposed to be caught by the
```
if gen.sizes["year"] > 1:
```
check this call is nested inside. I guess individual samples can have nans?

**Comment by mcgibbon** [comment]
Opened a quick PR ai2cm/full-model#666 to resolve this particular exception. I'm not sure it resolves all issues, but there are other checks already in the routine which I think will capture this for the means.

**Comment by oliverwm1** [comment]
What about just not even using the aggregator in the case of short runs? Like what we do for the "step 20" metrics.

https://github.com/ai2cm/full-model/blob/51688e893986097e1c7e7fd07bb8de6b115e6444/fme/fme/fcn_training/train.py#L344-L349

**Comment by mcgibbon** [comment]
Updated the PR to do this, but inside the InferenceAggregator using n_forward_steps. We should probably move record_step_20 in there as well.
