### ISSUE TITLE
Seasonal-mean bias metrics have opposite sign convention to time-mean bias metrics

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/ace#313]
The seasonal-mean bias metrics use `target - generated`:
https://github.com/ai2cm/full-model/blob/eb54a2fc58ce8ae1c58d4da172ded43a60f3c0cb/fme/fme/core/aggregator/inference/seasonal.py#L85
while the time-mean bias metrics use `generated - target`:
https://github.com/ai2cm/full-model/blob/eb54a2fc58ce8ae1c58d4da172ded43a60f3c0cb/fme/fme/core/aggregator/inference/time_mean.py#L23
We should make these consistent to help with interpretability—I prefer `generated - target` as is done in the time-mean case.  

For a concrete example of this issue, compare the seasonal-mean surface temperature bias plot in [this run](https://wandb.ai/ai2cm/fourcastnet/runs/7n3mf882) to the time-mean surface temperature bias plot (the negative bias in the equatorial Pacific shows up as a positive bias in the seasonal-mean plots).

**Comment by oliverwm1** [comment]
Good catch. The bias should definitely be prediction minus target!

**Comment by spencerkclark** [comment]
Sounds good—I made a quick PR to address this: https://github.com/ai2cm/full-model/pull/725.
