### ISSUE TITLE
Make the "fme" package more easily installable

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#325]
We don't currently use the dependencies specified in the `requirements.txt` in the "fme" package. This means a user (e.g. our docker image build) has to manually install the dependencies before installing the "fme" package. We had reasons for doing this (e.g. lets us ensure that "modulus" gets installed without its dependencies) but it makes it harder for others to install the `fme` package without using our particular install scripts / conda env. We should make our dependency specification simpler.

**Comment by mcgibbon** [comment]
If we were to update to the newer modulus architecture we now have in our repo and drop support for the previous architecture, we could avoid modulus installation issues entirely. That or vendorize our forked modulus code into our repo similarly to what we've done for makani.

**Comment by oliverwm1** [comment]
Agreed avoiding modulus installation would make this task a lot easier.
