### ISSUE TITLE
Save a "restart" file at end of every window (or just at end of full run?)

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#329]
The restart file should contain a snapshot of all prognostic variables, but not diagnostic or forcing variables. The format should be appropriate for use as an initial condition in a subsequent run.

Related: ai2cm/ace#258, since implementing ai2cm/ace#258 is necessary before this "restart" feature will be useful.

**Comment by mcgibbon** [comment]
Should this be more freely configurable? Having restart files at the start of each month, year, or season feels like a common use case, so we may want to be able to configure restart writes independent of window size (or even independent of a fixed number of steps between files), even if it's not that convenient to code.

**Comment by oliverwm1** [comment]
I think for now, let's have this feature be targeted at enabling checkpoint/restarting of long inference runs (versus generating a bunch of initial conditions for some future ensemble). So just need the restart to get saved at end of full run or at fixed interval throughout.
