### ISSUE TITLE
Clearer error if loader returns zero batches

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/ace#332]
I misconfigured a run to start one of the loader's subsets after the end of the available data, such that there were no validation batches. It wasn't clear that this was the cause of the ensuing error: `AttributeError: 'SnapshotAggregator' object has no attribute '_gen_data'`. An error describing that there were no batches would be more helpful.

**Comment by AnnaKwa** [comment]
Actually an informative error will be raised on initialization of the data loader if `n_samples`=0. In my case I had 7 samples but a batch size of 16 (i.e. zero batches) which didn't cause any issue until later on in the training.

**Comment by brianhenn** [comment]
Resolved by ai2cm/full-model#761, correct?
