### ISSUE TITLE
Validation loader length (number of batches) seems wrong when distributed

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#334]
For a multi-GPU case, if I configure the train and validation data to be identical (i.e., 1 ens member of 1 year of data each, both use `data_type: xarray`, and both set `batch_size` to the number of GPUs (here 2), I get something like the following [logged](https://github.com/ai2cm/full-model/blob/260490e6c60b613bc427be857aa3f9029c533e2e/fme/fme/ace/train.py#L98C1-L115C1) output:
```
2024-04-23 20:51:25,683 - root - INFO - train data: 1459 samples, 730 batches
2024-04-23 20:51:25,684 - root - INFO - valid data: 1459 samples, 1459 batches
```
In other words, the train data correctly describes the data as being of `batch_size` 2 (the configured `batch_size` and the distributed number of processes), but the validation data seems to think the `batch_size` is 1.

This appears to occur because we divide the batch size by number of distributed process for both train and validation data loaders, but then we pass a `DistributedSampler` to the loader only in the case of training, and not in the case of validation: [see code](https://github.com/ai2cm/full-model/blob/main/fme/fme/core/data_loading/getters.py#L64C1-L78C6).

This makes me wonder if validation is not actually being done with a parallel data loader? Seems possible for example that _each_ GPU is running _each_ validation sample (at a batch size 1/n_gpus smaller than configured).

**Comment by brianhenn** [comment]
The thing to test would be to pass a `DistributedSampler` to the validation loader and see if the logged batch size is correct, and whether validation is sped up.

**Comment by brianhenn** [comment]
Passing a `DistributedSampler` to the validation data loader does fix the number of batches issue, and slightly speeds up validation (33s vs 28s on this toy dataset):
- current non-distributed sampler validation data loader: https://wandb.ai/ai2cm/fourcastnet/runs/9xxxc32e
- distributed sampler validation data loader: https://wandb.ai/ai2cm/fourcastnet/runs/q2urku89

**Comment by oliverwm1** [comment]
Good catch. We should definitely get this fixed. I have noticed GPU util drop outs at the end of every epoch—might be related.
