### ISSUE TITLE
Number batches seen is off by one in downscaling

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#338]
L93: Should go at the end of the body of the loop

https://github.com/ai2cm/full-model/blob/19f47237dfa1a3631e140720aee57f5870615533/fme/fme/downscaling/train.py#L90-L102

**Comment by oliverwm1** [comment]
@gideonite we looked at a wandb run and determined there was actually no issue, right?

**Comment by gideonite** [comment]
That's right. Closing this issue
