### ISSUE TITLE
Use "Inference Mode" when doing inference

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#340]
pytorch has an "Inference mode" which is a more extreme version of "no-grad" mode. We should try using this as the context for inline and standalone inference, since it may lead to further speedups.

https://pytorch.org/docs/stable/notes/autograd.html#inference-mode

**Comment by AnnaKwa** [comment]
Over a 5 year inference, the change saves ~1.5 (out of ~165s) in the run_on_batch timing.
wandb run using inference_mode: https://wandb.ai/ai2cm/ace-debugging/runs/xcs9lj35/overview?nw=nwuserannakwa
" " using no_grad: https://wandb.ai/ai2cm/ace-debugging/runs/bq5d44nf

**Comment by oliverwm1** [comment]
Okay thanks for trying it out. I agree the very slight difference could just be noise and not worth merging this change for now.
