### ISSUE TITLE
Assert that dataset time coordinate is evenly spaced

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#341]
The ACE training/inference code implicitly assumes that the data going into `XarrayDataset` has a time coordinate that spans a start and end time with evenly spaced time interval, and has no missing times. We should add this assertion to the `XarrayDataset` init to make sure we are not unintentionally training or doing inference on datasets that do not satisfy this condition. 

We should also provide a config option to turn the check off, since it is not relevant for some uses (e.g. downscaling which does not require adjacent time steps).

**Comment by oliverwm1** [comment]
Somewhat related, ideally we would also get the time step from the dataset instead of hard-coding as a constant: ai2cm/ace#227

**Comment by spencerkclark** [comment]
One minor thing that came up when implementing this is that the method of repeating a dataset via `n_repeats` results in a time coordinate that violates this property.  I'll think about how to cleanly address that next week.  It seems like it could make  sense to generate a new time coordinate from the inferred frequency using the unrepeated files and `cftime_range`.  If we did that, though, we might also want some validation that there would not be a discontinuity in the annual cycle between repeats.

**Comment by oliverwm1** [comment]
Yes, the repeated time coordinate should get incremented properly for the `n_repeat > 1` case. Currently some outputs are wonky for `n_repeat` greater than 1 (e.g. the monthly mean data writer outputs). 

I'm not sure about doing validation... I'd probably lean to having a warning about this being an 'experts only' setting and assume that people are using appropriate datasets.
