### ISSUE TITLE
More flexible specification of ensemble dataset

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#353]
Currently we require that all the datasets which get concatenated into an "ensemble" dataset are within the same directory:

https://github.com/ai2cm/full-model/blob/00e0301a6ab6e7bd7320b19f84887443e3a046f1/fme/fme/core/data_loading/_xarray.py#L60-L66

but this is overly limiting (e.g. requires moving around datasets for particular experiments). Instead we should just have the user be verbose and write out the individual configs for each of the datasets that they wish to concatenate.

E.g. instead of current config:

```
@dataclasses.dataclass
class DataLoaderConfig:
    dataset: XarrayDataConfig
    batch_size: int
    num_data_workers: int
    data_type: Literal["xarray", "ensemble_xarray"]
    subset: Union[Slice, TimeSlice] = dataclasses.field(default_factory=Slice)
    n_samples: Optional[int] = None
    strict_ensemble: bool = True
```

I propose:

```
@dataclasses.dataclass
class DataLoaderConfig:
    dataset: Sequence[XarrayDataConfig]
    batch_size: int
    num_data_workers: int
    n_samples: Optional[int] = None
    strict_ensemble: bool = True
```
If we want to maintain backwards compatibility, we could also do `dataset: Union[XarrayDataConfig, Sequence[XarrayDataConfig]]`. Note the `data_type` item is deleted. I think we should also move the `subset` config option to be directly on `XarrayDataConfig` since that will allow providing a different subset option for each ensemble member.

**Comment by gideonite** [comment]
I think that this warrants a [design doc](https://docs.google.com/document/d/1kmVY4nn1vt_yOrYCeNM2nvQP8VIMChtoOshwpJ_cTlY/edit) for further discussion.

**Comment by gideonite** [comment]
I've scoped out two possible ways of implementing this in draft PRs. The first https://github.com/ai2cm/full-model/pull/844 has a bit more refactoring, the second is a bit more of a direct route https://github.com/ai2cm/full-model/pull/847.

**Comment by oliverwm1** [comment]
Thanks. My preference would be to go ahead with something like ai2cm/full-model#847, since there are multiple people in the group currently wanting to use this feature. And then the refactors can follow as needed. I agree they will result in code that is a bit easier to follow and much more consistent with other patterns in the codebase.
