### ISSUE TITLE
Allow configuring inference initial condition via timestamps

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#357]
Currently we have to provide a time index (plus interval and # of initial conditions) to configure the start times of inference, whether for inline or standalone. It would be convenient to alternatively be able to supply a sequence of timestamps, which the code could figure out how to convert into indices. Something similar already happens for the "subset" start/stop used for trainin/validation datasets (see https://github.com/ai2cm/full-model/pull/777).

The following line:

https://github.com/ai2cm/full-model/blob/cf2b0ed29255fee742e281171b717190f254a3e5/fme/fme/core/data_loading/inference.py#L59

could be changed to `start_indices: Union[InferenceInitialConditionIndices, TimestampList]`

where (roughly speaking...)
```
@dataclasses
class TimestampList:
    times: Sequence[datetime.datetime]

    def as_indices(self, time_index: xr.CFTimeIndex):
        return np.array([time_index.get_loc(t) for t in self.times])
```
and some code would need to be added to get the time index from the dataset.

**Comment by spencerkclark** [comment]
Yup, I think this is the right general idea.  

For greatest compatibility with different calendars it might be best if we could deserialize the times as strings and leave the parsing and conversion to `cftime` objects to `cftime.datetime.strptime`:

```python
>>> time_index = xr.cftime_range("2000", periods=5)
>>> FORMAT = "%Y-%m-%dT%H:%M:%S"
>>> time = "2000-01-01T00:00:00"
>>> cftime.datetime.strptime(time, FORMAT, calendar=time_index.calendar)
cftime.datetime(2000, 1, 1, 0, 0, 0, 0, calendar='standard', has_year_zero=False)
```

There are ways we could increase the flexibility of the date format, but I'm not sure if they are worth it.
