### ISSUE TITLE
`subset_dataset` function should propagate/subset the `time_index` property

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#368]
Since our `XarrayDataset` has various custom properties, we have a function which wraps `torch.utils.data.Subset` to propagate these custom properties:

https://github.com/ai2cm/full-model/blob/b74ec872f479c617587941a184e742b7b906e775/fme/fme/core/data_loading/_xarray.py#L49-L60

Although the `time_index` property is not currently used by any functions which consume a subsetted `XarrayDataset`, we should probably also propagate (and properly subset) the `time_index` property.

**Comment by AnnaKwa** [comment]
Just to confirm, is the desired behavior that the time_index (now sample_start_times) only include sample start times where the timesteps in the last sample all fall within the subsetted slice?
ex. if the full dataset times available are range(10) and n_timestep=5 (sample size) 
- the nonsubsetted dataset's sample_start_times=[0, 1, ..., 5]
- for a subset slice(2, 8) , the subsetted dataset's start times would be [2, 3]

**Comment by oliverwm1** [comment]
The subset slice is applied to the dataset's index which corresponds to the sample start times. This is is just defined by how pytorch does dataset subsetting (it doesn't really know anything about the time coordinate).

So for your case, I think the subsetted dataset start times would be [2,3,4,5] because that is what range(6)[slice(2,8)] gives you.
