### ISSUE TITLE
Time-mean inference aggregator returning wrong values

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#374]
Runs using an image since various refactors of the time-mean inference aggregator are showing weird values for the denormalized time-mean inference metrics (specifically, time-mean bias maps, global means and RMSEs). Other diagnostics (e.g. the zonal-mean bias) show reasonable results and are inconsistent with the time-mean maps, which is why I think this is a bug and not just a poorly performing model.

Run with new image: https://wandb.ai/ai2cm/fourcastnet/runs/br7b7afa/overview?nw=nwuseroliverwm (using https://github.com/ai2cm/full-model/pull/915/commits/180aae72d798e91d0aa424660c4e504b2b2621f6)
<img width="428" alt="Screenshot 2024-06-22 at 9 55 15 AM" src="https://github.com/ai2cm/ace/assets/23640870/17ad8ce3-f2eb-4a08-ad5e-1a3851cb002d">

Similarly configured run with old image: https://wandb.ai/ai2cm/fourcastnet/runs/mny583hy?nw=nwuseroliverwm (using https://github.com/ai2cm/full-model/pull/915/commits/73e74c2cf7ea80db43868f607810d1a7f365e90f)

<img width="428" alt="Screenshot 2024-06-22 at 9 55 42 AM" src="https://github.com/ai2cm/ace/assets/23640870/0edf9122-e442-4028-a053-b61c6ba512a6">

**Comment by oliverwm1** [comment]
@mcgibbon could you take a look.

**Comment by mcgibbon** [comment]
Concerning. Yes.

**Comment by mcgibbon** [comment]
I added a values unit test which passed. Given the magnitude of the bias (88 out of ~270), I'm suspecting it may be an error in the parallel reduction somehow. Will continue to investigate.

**Comment by mcgibbon** [comment]
This is proving difficult to reproduce in a unit test, and very difficult to debug without a unit test.
