### ISSUE TITLE
RuntimeWarning when running `python -m fme.ace.train`

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#376]
There is a RuntimeWarning when running the train entrypoint. This is a bit off-putting, can we resolve it? Is it related to how things are imported into `fme.ace.__init__`?

To reproduce:
```
(fme) oliverwm@OliverWeyersMBP ace % python -m fme.ace.train --help
/Users/oliverwm/miniconda3/envs/fme/lib/python3.10/runpy.py:126: RuntimeWarning: 'fme.ace.train' found in sys.modules after import of package 'fme.ace', but prior to execution of 'fme.ace.train'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
usage: train.py [-h] yaml_config

positional arguments:
  yaml_config

options:
  -h, --help   show this help message and exit
```

**Comment by mcgibbon** [comment]
Note this issue will also happen if `fme.ace.inference.evaluator` is run, but I will not fix it for that one, as it does not happen if `fme.ace.evaluator` is run so a reasonable fix is to move to that entrypoint.
