### ISSUE TITLE
TimeCoarsenConfig not listed in docs API

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#382]
When looking at the DataWriterConfig item in the API section of the docs, I noticed the `TimeCoarsenConfig` sub-class cannot be clicked and does not seem to be listed in the API.

https://friendly-engine-j54g3ez.pages.github.io/html/api.html#fme.ace.DataWriterConfig

**Comment by oliverwm1** [comment]
FYI @mcgibbon

**Comment by mcgibbon** [comment]
PR up: https://github.com/ai2cm/full-model/pull/982

Note the solution to this kind of issue is always to add the missing symbol to the `fme.ace` namespace, assuming it's meant to be public API (all config classes a user might interact with are meant to be public API). Docs for these things might appear on other doc pages, but only the automatic docs for the top-level namespaces get indexed/linked.

**Comment by oliverwm1** [comment]
> PR up: ai2cm/full-model#982
> 
> Note the solution to this kind of issue is always to add the missing symbol to the `fme.ace` namespace, assuming it's meant to be public API (all config classes a user might interact with are meant to be public API). Docs for these things might appear on other doc pages, but only the automatic docs for the top-level namespaces get indexed/linked.

Thanks!
