### ISSUE TITLE
Add proper handling for aggregation across HorizontalDimensions, not just lat/lon

### ISSUE THREAD

**Issue by anna-dodson** [ai2cm/ace#389]
In trainer.py, we have
        train_aggregator = Aggregator(
            self.area_weights.fine.cpu(), self.latitudes, self.model.downscale_factor
        )
        validation_aggregator = Aggregator(
            self.area_weights.fine.cpu(),
            self.latitudes,
            self.model.downscale_factor,
        )
        generation_aggregator = Aggregator(
            self.area_weights.fine.cpu(),
            self.latitudes,
            self.model.downscale_factor,
        )

We would like this to be able to aggregate across other horizontal coordinate systems.

**Comment by oliverwm1** [comment]
Is this issue still open? There were many PRs generalizing the aggregators to handle more general grid. The code snippet copied is from the downscaling code, which does not need to be generalized to other coordinate systems.

**Comment by anna-dodson** [comment]
Yeah this is done with ai2cm/full-model#995 and its follow ups I believe.
