### ISSUE TITLE
Avoid emitting MSE-related warnings on validation

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#393]
Possible that I've misconfigured something in recent SHiELD-AMIP training jobs, but the logs from the validation step have extensive warnings about MSE-related variables not being present ([example](https://wandb.ai/ai2cm/ace/runs/cnp6qofi/logs), looks like maybe 4x warnings per batch of the validation loader). Presumably we don't want to emit that warning in this context.

**Comment by AnnaKwa** [comment]
I overlooked adding the required forcing inputs in the validation call of `compute_derived_variables`, so I'm fixing this in a PR that addresses multiple issues with the MSE variables.

**Comment by AnnaKwa** [comment]
For cases where the required forcing input is still missing from the forcing data, I'll lower the logging level to debug so it doesn't clog up the logs.
