### ISSUE TITLE
 Missing InitialConditionConfig explanations on inference behavior in docs

### ISSUE THREAD

**Issue by frodre** [ai2cm/ace#397]
The current initial conditions expectations and resulting code behavior are not well defined in the documentation.  I.e., the code makes it clear that there must be a time dimension, and that it will run the number of IC times present in the data as simultaneous simulations. https://github.com/ai2cm/full-model/blob/bc6c840aa18a69b8ec5888aaec82793880de0885/fme/fme/ace/inference/inference.py#L50

I plan on adding this to the documentation description in `inference_config.rst` and the docstrings for `InitialConditionConfig`.

**Comment by AnnaKwa** [comment]
I'll work on adding an option to specify indices or timestamps to subselect from the full set of possible ICs in the dataset, that would be a useful feature.

**Comment by oliverwm1** [comment]
Is this issue still open? Looks like there is a docstring for InitialConditionConfig now.
