### ISSUE TITLE
Jobs hang on wandb upload after final epoch

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#398]
I have had two jobs on the jupiter cluster which finished their last epoch, but then did not gracefully shut down. It seems they got stuck on uploading the wandb metrics (although as far as I can tell, all the metrics are available). This is bad because it occupies GPUs without using them.

Example: https://beaker.org/ex/01J2FCVSDJHJY8WGTZ7KSYJAWR/tasks/01J2FCVSDS8SV2CSGE4NE885YG/job/01J30NQXWMTD3Q8Y7K4551FM5T

Tail of logs:
```
wandb: / 3859.464 MB of 3859.464 MB uploaded
wandb: - 3859.464 MB of 3859.464 MB uploaded
wandb: \ 3859.464 MB of 3859.464 MB uploaded
wandb: | 3859.464 MB of 3859.464 MB uploaded
wandb: / 3859.464 MB of 3859.464 MB uploaded
wandb: - 3859.464 MB of 3859.464 MB uploaded
wandb: \ 3859.464 MB of 3859.464 MB uploaded
wandb: | 3859.464 MB of 3859.464 MB uploaded
wandb: / 3859.464 MB of 3859.464 MB uploaded
wandb: - 3859.464 MB of 3859.464 MB uploaded
wandb: \ 3859.464 MB of 3859.464 MB uploaded
wandb: | 3859.464 MB of 3859.464 MB uploaded
wandb: / 3859.464 MB of 3859.464 MB uploaded
wandb: - 3859.464 MB of 3859.464 MB uploaded
wandb: \ 3859.464 MB of 3859.464 MB uploaded
wandb: | 3859.464 MB of 3859.464 MB uploaded
wandb: / 3859.464 MB of 3859.464 MB uploaded
wandb: - 3859.464 MB of 3859.464 MB uploaded
wandb: \ 3859.464 MB of 3859.464 MB uploaded
wa
```

**Comment by mcgibbon** [comment]
https://github.com/wandb/wandb/issues/4929

**Comment by mcgibbon** [comment]
According to a [comment in the wandb issue](https://github.com/wandb/wandb/issues/4929#issuecomment-2195850571) from 3 weeks ago, [wandb-core](https://github.com/wandb/wandb/blob/main/core/README.md) resolves this.

**Comment by brianhenn** [comment]
Had another [job](https://beaker.org/ex/01J3W4VQQREBQEHTSWYE4GB8XC/tasks/01J3W4VQQWSNVKTBYN12AP41V6/job/01J3YPET1PMSPPVH1G5M2P5RGQ) on jupiter that hit this. Unfortunately it did not succeed in actually uploading the results to wandb, apparently (a bit hard to tell because the job was pre-empted 29 times!, frequently in the wandb upload phase).

**Comment by oliverwm1** [comment]
Good to know. We should probably just switch to new backend, which apparently will be the default soon anyway.

**Comment by oliverwm1** [comment]
Also... we should probably think about reducing our # of metrics, especially images. Maybe we only log images every 5 epochs? Or for a smaller set of variables?
