### ISSUE TITLE
HEALPix should detect prognostic variables automatically

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#418]
The HEALPix model currently requires prognostic variables be configured independently of the stepper input/output config. Instead, we should automatically determine the prognostic variables from the stepper config, and pass this data along to the healpix build method. This could take the form of a prognostic variable count, but could also take the form of passing the in_names and out_names to the builder.

**Comment by anna-dodson** [comment]
https://github.com/ai2cm/full-model/pull/1065/files#r1719869905

**Comment by oliverwm1** [comment]
Is this a duplicate of ai2cm/ace#409?

**Comment by mcgibbon** [comment]
Yes. Closed as duplicate.
