### ISSUE TITLE
Make `StandardNormalizer` data device consistent 

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/ace#419]
Right now, the `StandardNormalizer.means` and  `StandardNormalizer.stds` are on CPU if training is initiated from scratch, and on device if initiated from an existing checkpoint. The latter case is because of the [cast to device](https://github.com/ai2cm/full-model/blob/efcedf5aeb7c9e7d1cca7b8777eccb9cc97319e9/fme/fme/core/normalizer.py#L116) in `StandardNormalizer.from_state` that is called when loading from the saved checkpoint. 

This difference doesn't currently cause issues in training, but can be confusing when tracing the data through the code flow. For example, [this PR](https://github.com/ai2cm/full-model/pull/1066) brought up the question of why the fresh training did not error when the normalizer was on CPU and was able to be used on data that was on GPU.

An easy change would be to cast the mean and std to device at initialization so all normalizer data is on device regardless of training initialization.

**Comment by AnnaKwa** [comment]
For posterity, copying the slack conversation that explains why the above device mismatch does not raise an error:

>  in the case of the fresh training normalization calls, it looks like it's because the normalizer mean and std are scalars which are a special case that can be used directly with tensors that are on GPU.
https://discuss.pytorch.org/t/can-tensors-on-different-devices-add-together/146221/2

> This is what the data and normalizer look like when .normalize is called:
> (Pdb) self.normalizer.means['air_temperature_0'].device
> device(type='cpu')
> (Pdb) gen_data['air_temperature_0'].device
> device(type='cuda', index=0)
> (Pdb)  self.normalizer.means['air_temperature_0']
> tensor(222.9613)
> (Pdb) diff =  gen_data['air_temperature_0'] - self.normalizer.means['air_temperature_0']
> Or more explicit demonstration:
> (Pdb) scalar_cpu = torch.tensor(1, device='cpu')
> (Pdb) tensor_gpu = torch.tensor([2,3], device='cuda')
> (Pdb) tensor_gpu - scalar_cpu
> tensor([1, 2], device='cuda:0')
> (edited)
> 
> 
> In the case that was broken for checkpoints, the tensor was on CPU and the scalar was on GPU, which does not work automatically:
> (Pdb) scalar_gpu = torch.tensor(2, device='cuda')
> (Pdb) tensor_cpu = torch.tensor([4,5], device='cpu')
> (Pdb) tensor_cpu - scalar_gpu
> *** RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by brianhenn** [comment]
IMO we could take this opportunity to get rid of the `FromStateNormalizer`. It seems like it duplicates the functionality of the   `NormalizationConfig`/`StandardNormalizer`, which [already](https://github.com/ai2cm/full-model/blob/efcedf5aeb7c9e7d1cca7b8777eccb9cc97319e9/fme/fme/core/normalizer.py#L32-L33) has the capability of taking in mappings of strings to floats for the mean and std, and then building the normalizer through the normal `build` method. Not having two different methods of initializing the `StandardNormalizer` would make it much less likely that the data would be handled differently as it is here.
