### ISSUE TITLE
Healpix implementation of aggregation

### ISSUE THREAD

**Issue by anna-dodson** [ai2cm/ace#422]
In developing our HEALPix model integration, we currently use an area_weights of None to ignore creating most of our aggregators since they are not configured to work with the dimensions of healpix data.

We should extend functionality to these (face, width, height) data in order to have a full set of metrics.

**Comment by mcgibbon** [comment]
For now we are not planning to implement the video, zonal mean, or spherical power spectrum aggregators for HEALPix. ai2cm/full-model#1096 will add support for all other aggregators.
