### ISSUE TITLE
Remove `FromStateNormalizer`

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#423]
I would propose removing the `FromStateNormalizer`. It duplicates the functionality of the `NormalizationConfig`, which [has](https://github.com/ai2cm/full-model/blob/efcedf5aeb7c9e7d1cca7b8777eccb9cc97319e9/fme/fme/core/normalizer.py#L32-L33) the capability of taking in mappings of strings to floats for the mean and std, and then building the `StandardNormalizer` through the `build` method that we typically use. Since ai2cm/full-model#1077, a previous difference between `FromStateNormalizer.from_state` and `NormalizationConfig.build` in terms of whether values were sent to GPU (which we presumably didn't want anyway) no longer exists.

**Comment by oliverwm1** [comment]
I've also been confused by `FromStateNormalizer`. I'd support this change.
