### ISSUE TITLE
Power spectrum aggregator works only with one data grid

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#426]
This is definitely a fringe issue, but currently it's not possible on main to run "dataset inference" using both ERA5 and SHiELD-AMIP (either one as the target and the other as the prediction). That's because the `SphericalPowerSpectrumAggregator` is initialized with a `.sht` method that is grid-dependent, and will fail on the other dataset's grid. 

Not sure if there's an easy fix for that. I got around it temporarily by commenting out the power spectrum aggregator, so we could make its usage configurable.

```
19 2024-08-16 20:42:59,053 - root - INFO - Inference: starting window spanning 0 to 40 steps, out of total 14600.
20 Traceback (most recent call last):
21   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
22     return _run_code(code, main_globals, None,
23   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
24     exec(code, run_globals)
25   File "/full-model/fme/fme/ace/evaluator.py", line 11, in <module>
26     main(
27   File "/full-model/fme/fme/ace/inference/evaluator.py", line 186, in main
28     return run_evaluator_from_config(config)
29   File "/full-model/fme/fme/ace/inference/evaluator.py", line 249, in run_evaluator_from_config
30     timers = run_dataset_comparison(
31   File "/full-model/fme/fme/ace/inference/loop.py", line 366, in run_dataset_comparison
32     _inference_internal_loop(
33   File "/full-model/fme/fme/ace/inference/loop.py", line 148, in _inference_internal_loop
34     aggregator.record_batch(
35   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
36     return func(*args, **kwargs)
37   File "/full-model/fme/fme/core/aggregator/inference/main.py", line 329, in record_batch
38     aggregator.record_batch(
39   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
40     return func(*args, **kwargs)
41   File "/full-model/fme/fme/core/aggregator/inference/spectrum.py", line 73, in record_batch
42     self._target_aggregator.record_batch(target_data)
43   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
44     return func(*args, **kwargs)
45   File "/full-model/fme/fme/core/aggregator/inference/spectrum.py", line 29, in record_batch
46     power_spectrum = spherical_power_spectrum(data[name], self._real_sht)
47   File "/full-model/fme/fme/core/metrics.py", line 380, in spherical_power_spectrum
48     field_sht = sht.forward(field)
49   File "/full-model/fme/fme/sht_fix.py", line 149, in forward
50     xout[..., 0] = torch.einsum('...km,mlk->...lm', x[..., :self.mmax, 0], self.weights)
51   File "/usr/local/lib/python3.10/dist-packages/torch/functional.py", line 378, in einsum
52     return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
53 RuntimeError: expected scalar type Float but found Double
```

**Comment by oliverwm1** [comment]
I thought these datasets had the same grid. Or at least that was the intention when I wrote the pipeline to generate the ERA5 data. So a bit confused about why it is failing. But yes, making it configurable is reasonable.

**Comment by mcgibbon** [comment]
I don't understand the error - it doesn't seem to have to do with a grid? It's complaining about incorrect precision.

**Comment by brianhenn** [comment]
Yeah the error is a bit in the weeds, and I'm not entirely sure why we're hitting this. It could be that the ERA5 and SHiELD coordinates are being saved with different types. I get `dtype('<f8')` for the SHiELD netCDF latitude and `dtype('float64')` for the ERA5 one, which seems like it should be the same but perhaps is not.

**Comment by brianhenn** [comment]
Actually the coordinate dtypes are the same (was comparing a zarr to a netCDF previously), so that's not it. Will have to launch debugging runs comparing the two datasets to see what's happening. Presumably there must be some float vs. double difference between the datasets somewhere given the error, but I agree now that it's probably not the grid being different.

**Comment by oliverwm1** [comment]
Hmm I also just hit this issue when doing 'data comparison' inference, but even just comparing the ERA5 dataset against itself. Seems to be a regression since I have done this previously.

https://beaker.org/api/v3/jobs/01J5RPFPP51X593JGMD8F9YQJM/logs?tail=2

**Comment by brianhenn** [comment]
Interesting so it's just that the ERA5 data are in some way incompatible with the aggregator. But you don't hit the error if ACE is the prediction and ERA5 is the target? I didn't hit it when running the evaluator with ACE as a prediction and SHiELD-AMIP as the target, on I think the same [commit](https://github.com/ai2cm/full-model/commit/c9e1605982065ade2c280f180555cd95bb66a31b) as when I did hit it with ERA5 vs. SHiELD-AMIP.

**Comment by oliverwm1** [comment]
Correct, I only hit it when using the dataset comparison style run, not when running the evaluator against the ERA5 dataset.

**Comment by brianhenn** [comment]
OK, maybe I will try launching the dataset comparison style run with SHiELD-AMIP only, since it's been a few commits since I did that.

**Comment by brianhenn** [comment]
I the dataset comparison run of SHiELD-AMIP against itself on a recent commit (22376640f5c867d86ff8296bc72de9f404e56a36) and it didn't hit this. So it's something specific to the ERA5 dataset in dataset comparison mode. I wonder if the various dtype casting changes we've made recently may have influenced/fixed this.

**Comment by brianhenn** [comment]
I reran the SHiELD-AMIP vs ERA5 dataset comparison [workflow](https://beaker.org/ex/01J830Y8ZNWMBTR33HY8CMF453/tasks/01J830Y8ZWC8589BQH0X7Y7MF6/job/01J830Y951GPKJZF6Q8YKZK5G2) on a commit on a branch off recent main (be5c49d7463e9ac6d9d2bc54c93fdf595e3f190a) and no longer hit the error. Perhaps this is fixed now. @oliverwm1

**Comment by oliverwm1** [comment]
Thanks for reporting. Yeah let's just close this and can reopen if anyone hits it again.
