### ISSUE TITLE
Data loaders should build their time dimensions based on the input/output time windows

### ISSUE THREAD

**Issue by anna-dodson** [ai2cm/ace#448]
In data loaders we should load total number of timesteps equal to (n_in/out steps) * (n forward steps + 1). Currently we assume that the number of input and output steps is just 1, so the data loader is a set size of (n forward steps + 1). 

This will enable variable number of in/out time steps, which is required for HEALPix.

**Comment by mcgibbon** [comment]
In implementing this, the data loader should be kept ignorant of any time stepping concerns and receive only the size of the windows it needs to load. It's the responsibility of the stepper to interpret the configuration and tell the data loader "give me windows with this number of forward steps" (i.e. windows of length n_forward_steps + 1) by providing a DataRequirements. "forward steps" here in DataRequirements only refers to a dataset timeseries length, and is different in meaning from "this is how many times the torch module gets called to step forward".

**Comment by AnnaKwa** [comment]
Closing since we agreed to basically do the above comment and removed this feature from the PR (https://github.com/ai2cm/full-model/pull/1178#pullrequestreview-2297976328)
