### ISSUE TITLE
Python logging changes: all ranks print WARNING, no INFO level messages

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/ace#452]
I noticed that training jobs weren't showing the INFO level logging statements that they were before.
[log from training job from a couple weeks ago](https://beaker.org/api/v3/jobs/01J70CKHZQVEZA5VA5SHX4FFZ7/logs?tail=2)
[log from training job based off recent main image](https://beaker.org/api/v3/jobs/01J7PKQMH5YPVWEXM15K2GQPYA/logs?tail=2)

Notably, the WARNING level logging is also printed `n_gpu` times, with all instances thinking they are root. 
 

This also happens in interactive jobs; I ran a short training job in a session and the disappearing INFO logging first occurs in [this commit](https://github.com/ai2cm/full-model/commit/4798f1cc8c83543b3a21d0f22f9c3de1d7d815fe). All those changes seem pretty benign but maybe somehow they caused some unexpected behavior- @jpdunc23 any ideas?

**Comment by jpdunc23** [comment]
@AnnaKwa I took a look but nothing is jumping out to me. Have you been able to reproduce this regression in a test?

**Comment by AnnaKwa** [comment]
Interestingly I cannot reproduce the desired logging behavior in the training unit test using either commit. It looks like the older commits that had the expected behavior in actual production training jobs also have the weird logging in pytest. Enabling `log_cli = true` for the unit tests, both commits 4798f1c (prod jobs stop outputting INFO level) and 32df85e (preceding commit) have the current behavior (only log at warning level, x n_gpu for each warning):
```
../../../../../full-model/fme/fme/ace/test_train.py::test_train_and_inference_inline[SphericalFourierNeuralOperatorNet] 
------------------------------------------------------------------------------------------------ live log call -------------------------------------------------------------------------------------------------
WARNING  root:logging_utils.py:116 Environmental variable BEAKER_EXPERIMENT_ID not found.
WARNING  root:logging_utils.py:116 Environmental variable SLURM_JOB_ID not found.
WARNING  root:logging_utils.py:116 Environmental variable SLURM_JOB_USER not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_TRAIN_DIR not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_VALID_DIR not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_STATS_DIR not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_CHECKPOINT_DIR not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_OUTPUT_DIR not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_IMAGE not found.
WARNING  root:logging_utils.py:135 Beaker Experiment ID not found.
WARNING  root:logging_utils.py:116 Environmental variable BEAKER_EXPERIMENT_ID not found.
WARNING  root:logging_utils.py:116 Environmental variable SLURM_JOB_ID not found.
WARNING  root:logging_utils.py:116 Environmental variable SLURM_JOB_USER not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_TRAIN_DIR not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_VALID_DIR not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_STATS_DIR not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_CHECKPOINT_DIR not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_OUTPUT_DIR not found.
WARNING  root:logging_utils.py:116 Environmental variable FME_IMAGE not found.
WARNING  root:logging_utils.py:135 Beaker Experiment ID not found.
```
in the above case the tests were run with 2 gpus. I also turned on the wandb logging flag in the unit test and verified that it was logging to wandb, since by default it is False. This didn't change the unit test logging output.

However, running a training job interactively via `torchrun --nproc_per_node 2 -m fme.ace.train ...` with the older commit (32df85e) does have the original behavior while commit 4798f1c has the issue.

**Comment by jpdunc23** [comment]
I'm also having this issue during training on Perlmutter: https://wandb.ai/ai2cm/jamesd-dev/runs/8b6r2pzr/logs

**Comment by oliverwm1** [comment]
This is also happening during an inference job: https://beaker.org/ex/01J9Q604W3851Y3AJW90M3XHH6/tasks/01J9Q604WAKTZ1V95G4EHYKG8Q/job/01J9Q60513TC7BQC5GVND87B4T and https://wandb.ai/ai2cm/ace/runs/13c5j39f/logs

**Comment by elynnwu** [comment]
Just ran with current main: https://wandb.ai/ai2cm/ace/runs/m4bdng9s/logs. Regular inference job did not have this issue, but able to reproduce when adding `--segments`. Looking into this now.

**Comment by oliverwm1** [comment]
> Regular inference job did not have this issue, but able to reproduce when adding --segments. Looking into this now.

weird... this is a mysterious one.

**Comment by elynnwu** [comment]
Inference with segments show logging info now. I was not able to reproduce this error in training on perlmutter, will try a run on beaker.

**Comment by elynnwu** [comment]
Both current main (c73f80ba3b7a7fba7bf49d2676f021b2f7134fe1) and https://github.com/ai2cm/full-model/commit/4798f1cc8c83543b3a21d0f22f9c3de1d7d815fe showed logging info on perlmutter (interactive jobs).

**Comment by elynnwu** [comment]
Submitted the job same way as James on perlmutter, still can't reproduce the error. See [log](https://wandb.ai/ai2cm/fourcastnet/runs/lj21doqv/logs).

**Comment by elynnwu** [comment]
Okay reproduced through beaker [here](https://beaker.org/ex/01J9WAKXFR6JXCQD391MX30Y5D/tasks/01J9WAKXFXDMGXTR3BZFE998X1/job/01J9WAKXN6Z20MPJ0EGSRJ9518).

**Comment by jpdunc23** [comment]
I don't think this is a `distributed` issue (if it were, we'd have 8 separate wandb jobs, right?) but might be worthwhile to see the logs with `export NCCL_DEBUG=INFO` to verify that the GPUs are being coordinated properly.

**Comment by elynnwu** [comment]
Logging info is [back](https://beaker.org/api/v3/jobs/01JAEZR74X4RZX6HPS6E4KPBCJ/logs?tail=2)! We should not have logging calls before the level is set in configure logging, it causes some sort of overwrite.
