### ISSUE TITLE
Window Stitcher needs to handle larger IC windows

### ISSUE THREAD

**Issue by anna-dodson** [ai2cm/ace#458]
Currently the WindowStitcher assumes there is not a time dimension in the data to be stitched. In order to properly write and save ICs of more than one timestep, we need the WindowStitcher to slice the data, not select it; and handle the additional dimension.

**Comment by mcgibbon** [comment]
Specifically `stitcher.save_initial_condition` needs to handle an initial condition that has a time dimension as its second dimension (index 1), both for ic_data and ic_time.

**Comment by oliverwm1** [comment]
Closing this since `WindowSticher` no longer exists, and the current data writer `save_initial_condition` function can handle data with a time dimension.
