### ISSUE TITLE
`inference/time_mean_norm/rmse/channel_mean` metric includes derived variables

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/ace#476]
In my current training jobs with `main`, e.g. [this one on WandB](https://wandb.ai/ai2cm/ace-som/runs/qa3l97p6), the `inference/time_mean_norm/rmse/channel_mean` metric appears to include derived variables (which are un-normalized).  This is evidenced by its scale, and the fact that it generally follows the trajectory of the `inference/time_mean/rmse` metric for `column_moist_static_energy`, which is the largest magnitude derived variable we track. See the left two panels in the screenshot below:

<img width="1565" alt="Screenshot 2024-10-26 at 4 40 32 PM" src="https://github.com/user-attachments/assets/8429e50f-b4d0-4a96-999a-8c73e73e10dc">

The `inference/time_mean_norm/rmse/*` metrics for individual prognostic or diagnostic variables are unaffected, e.g. for `air_temperature_0` on the right.

This unfortunately affects checkpoint selection, so it is a fairly critical bug to fix.  A bisect suggests #1199 is the culprit.  For now I will resubmit these training jobs from the commit before.

**Comment by oliverwm1** [comment]
Good catch. Indeed we should have a check that only "non derived" variables get included. I'm somewhat surprised that column MSE is getting included since I would have thought that there would not be any normalization statistics for this name, and so the normalized variables would not include this variable.

**Comment by spencerkclark** [comment]
Yeah I looked into this a little bit, since I was surprised too.  Apparently if there is a variable name that does not exist in the normalization statistics, we let the variable pass through unmodified, rather than drop it or raise an error:
https://github.com/ai2cm/full-model/blob/a7d403094a1f87715cfa29168f59678afe9e8049/fme/fme/core/normalizer.py#L127-L136

**Comment by oliverwm1** [comment]
oh wow... I always thought we dropped it (which is why I was not super worried about this kind of issue popping up, although obviously still a potential risk given who knows what people will have in their normalization statistics). I would definitely prefer to drop than current behavior.
