### ISSUE TITLE
run_dataset_comparison moves data to GPU

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#484]
[link](https://github.com/ai2cm/full-model/pull/1317#pullrequestreview-2416609416)
> Finally, this is a pre-existing issue, but it is odd that in run_dataset_comparison we move all data to GPU when we don't actually need to do any ML inference. It seems this PR would make that even harder to undo.

**Comment by oliverwm1** [comment]
We've decided this is a non-goal, because running the dataset comparison on GPU is faster.
