### ISSUE TITLE
Remove compute_derived_variables from BatchData

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#488]
`compute_derived_variables` requires some torch tensors to be saved which can cause issues when attached to BatchData, as BatchData must be CPU-only during data loading and we usually want these tensors on the current device. We should move this functionality back off of BatchData by having it in the stepper (and Deriver for data comparison).

**Comment by oliverwm1** [comment]
This was resolved by ai2cm/full-model#1363
