### ISSUE TITLE
Recent checkpoint backwards incompatibility

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#490]
A recent checkpoint (one of the ACE2 paper models) fails on evaluation on current main when loading with a stepper config `exclude_names` objection (`exclude_names` was saved with previous checkpoints but [recently](https://github.com/ai2cm/full-model/pull/1292/files#diff-79d90a549afa8aa27af9859d5856563dbe88af21a9d5067fb0ccf671fe4aa5e0) removed). See [error logs](https://beaker-web.allen.ai/orgs/ai2/workspaces/ace/work/01JCEE0XDHCYPMGNWXEA3PVJ01/logs?jobId=01JCEE0XJX933280DYZWEYY5JP). 

While there's a backwards compatible [check](https://github.com/ai2cm/full-model/pull/1303/commits/7cc7a986db0f2fc4c34d6696315b0563c52ac5be) for empty `exclude_names` attributes under the main normalizer configuration, that error is not raised here. I think we're hitting the same issue but on the `loss_normalization` or `residual_normalization` stepper config attributes that also use the `NormalizerConfig` but lack such a check.

**Comment by oliverwm1** [comment]
Yes, should add the `loss_normalization` and `residual_normalization` items to the "remove deprecated keys" function. Can add a loop over `normalization`, `loss_normalization` and `residual_normalization` where we currently just check for and fix `normalization`.
