### ISSUE TITLE
GPU memory usage jumped up (>80GB for ACE2 config) on recent main

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#500]
GPU memory usage appears to have increased substantially training in the ACE2 configuration. GPU OOM on 80gb H100s. It appears to be due to code changes on recent main, i.e.,:

- current/recent main (af9808ac and more recent) produces 80gb GPU memory error in ACE2 train configuration (2 samples/GPU, 2 forward steps etc): [experiment](https://beaker.allen.ai/orgs/ai2/workspaces/ace/work/01JDB2J0H930XYP4MHCVKNVGZH?taskId=01JDB2J0HF3VJ3D8D1J0Z6CADD&jobId=01JDB2J0QB8C81B7PJJKFMS5MR), [wandb](https://wandb.ai/ai2cm/ace/runs/ff4vfi99)
- this does not happen for eg e7faf118, only about 60% of GPU memory used: [experiment](https://beaker.allen.ai/orgs/ai2/workspaces/ace/work/01JDB74VJR2W0D830PKQ7PQYCG?taskId=01JDB74VKC95VV02YTST35BKQH&jobId=01JDB74VSQ35PPEQ61041AE6HZ), [wandb](https://wandb.ai/ai2cm/ace/runs/3g2idssp)

Unclear what caused this since the commits don't seem that related to GPU memory.

**Comment by mcgibbon** [comment]
I don't know if the beaker folks would like it, but it may be good to automatically launch a small production training job on each commit to main so we can monitor performance metrics like this.

**Comment by mcgibbon** [comment]
Also worth pointing out this happens when training begins, which is unexpected because I thought it might be due to changes in inference data handling, but it must not be.

**Comment by oliverwm1** [comment]
Yikes, thanks for reporting. Agreed it is surprising. Would be very helpful to narrow it down to a single commit out of the three that could currently be responsible (i.e. ccda29a84e2c95255151dcd088877aa0175e235c, 56312e69c949f63f5f40b3f6bb55e1a0e5dc1085 or af9808acf141890f0cfdc988d3b0ef1f14eed313).

![Screenshot 2024-11-25 at 2 10 50 PM](https://github.com/user-attachments/assets/cd277eb7-7824-466b-a4cc-0d47987f0332)

**Comment by oliverwm1** [comment]
Note that it is possible that it is unrelated to the commits, since we don't pin all our dependencies, so it could be some change in a dependency between when you built these images. That said... we do pin `torch` which would seem like the most likely culprit and also seems unlikely to let through such a regression!

**Comment by brianhenn** [comment]
Figured out the issue, [this](https://github.com/ai2cm/full-model/pull/1365) commit inadvertently switched the number of forward steps in training to the number forward steps in inference. Fix [here](https://github.com/ai2cm/full-model/pull/1396).
