### ISSUE TITLE
Remove `Device` classes and corresponding type hinting

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#506]
From @mcgibbon on slack:

> Personally I'm leaning towards removing the type hinting but keeping the "GriddedData exposes on-fme-device objects" change which I think gives us a lot of safety. Mostly because the hinting doesn't seem to be caught most of the time.

For simplicity and ease of development, let's remove the `AnyDevice`, `CPUDevice` and `CurrentDevice` classes and corresponding type hints. In addition, we should also make it clear in the docstring of `GriddedData` and `InferenceGriddedData` that these classes move everything to device during init.

**Comment by mcgibbon** [comment]
I will also keep the `new_on_` methods as ways to initialize, as they help document intent and ensure device location when used.
