### ISSUE TITLE
Bug in `OneStepAggregator` usage with `SingleModuleStepper.train_on_batch()`

### ISSUE THREAD

**Issue by jpdunc23** [ai2cm/ace#516]
Output from `SingleModuleStepper.train_on_batch()` used to include initial conditions and sub-aggregators of  `fme.ace.aggregator.OneStepAggregator` assume that's still the case. As a result, the first forward step is treated as if it were the initial condition.

**Comment by oliverwm1** [comment]
Yikes, good catch. I thought we were now pre-pending the initial condition data outside of `train_on_batch` before passing the one-step aggregator, but indeed we're not. Would it make sense to have an argument to `train_on_batch` that allows returning data including the initial condition I.e. an option to not do this: https://github.com/ai2cm/full-model/blob/694300ff7c90e0bbb94933be07e4e0e279ca22c7/fme/fme/ace/stepper.py#L856

I thought we had this at some point—don't remember why we now have train_on_batch not return IC. @mcgibbon

**Comment by mcgibbon** [comment]
Ah, the behavior I meant to maintain was that train_on_batch should always (rather than never) retain the initial condition, which was my understanding of how the code worked before. We should restore this behavior.

**Comment by oliverwm1** [comment]
I'd be good with that!
