### ISSUE TITLE
Add type hinted adapters for external dependencies

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#76]
Currently it's difficult to reason about how to work with the external types we've been provided. One option would be to add type hinting directly into the fourcastnet code, but this runs the risk of excess merge conflicts in the future.

Instead, we will define Protocol types corresponding to the tools in the fourcastnet code base we plan to use. For example, we should define Protocol types for `FourierNeuralOperatorNet` and its `params` argument.

Once this is done, we will define a wrapper class over the external dependency which makes its APIs cleaner (e.g. only one way to pass arguments, likely via a dataclass) and has type hinting and docstrings.

**Comment by oliverwm1** [comment]
I would probably vote for just directly modifying the fourcastnet code if it will lead to less indirection. In particular if we restrict ourselves to just making changes in the `sfnonet.py` module, this seems like it will be easy enough to manage possible conflicts. I'd be more hesitant about making widespread changes in the `torch_sht` and `modulus-core` packages within `fcn-mip`.

**Comment by oliverwm1** [comment]
> Currently it's difficult to reason about how to work with the external types we've been provided.

I think this is the point I don't really follow. Maybe we should chat offline.

**Comment by oliverwm1** [comment]
I believe this is resolved, since we now have type-hinted "builder" classes for each model type. Feel free to reopen if there's something else to do.
