### ISSUE TITLE
Try training on more idealized datasets

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#86]
Some idealized test cases we have discussed:

1. Overfit on a single sample. This would be focused on offline (1-timestep) prediction.
2. Train on identity dataset (input==output) and see if long rollouts maintain this constant value
3. Train on flip-flop. The dataset would have two snapshots, which would be ordered in the training data as three timesteps (snapshot0, snapshot1, snapshot0) so that the two input/output samples in our dataset would be 0->1 and 1->0. The hope is that the model would flip back and forth between these states, including in long rollouts.

I believe these cases are all possible with our current code—it's just a matter of setting up netCDF datasets that have the right data. We could also generate synthetic data, or write some custom code to generate these datasets somehow. But I'd probably start by just manually creating the datasets and training configurations and using our existing training infrastructure to test out these cases and get some intuition.

For the long rollouts, I believe the inference code does assume that the validation data is longer than the inference rollout, so we would need to make sure we create a validation dataset with the data repeated as necessary if we want to avoid code changes.

**Comment by gideonite** [comment]
Longer discussion here: https://docs.google.com/document/d/1fj3AMFSdykG7w4u4K9yH2zIqcTZ9u7Q_cPCVA3i2OZU/edit
