### ISSUE TITLE
s/beaker.yaml/beaker.py/

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#92]
Our current setup uses yaml configs and bash scripts to create immutable training / inference configs that are tied to particular experiments. While this setup has gotten us really far, as we begin to ramp up our experiments we are going to need a simpler, more configurable setup. The beaker python API looks very useful for achieving this. 

I think that this will require some discussion and as we are not quite at the stage when we need this kind of infra, I am putting this as low priority. If there's time to start having this discussion, perhaps this would be a good place to track it.

**Comment by gideonite** [comment]
I started this since I was trying a few different learning rates. It doesn't work yet.

**Comment by oliverwm1** [comment]
I've also found beaker-py convenient for scripting the submission of multiple related experiments, so I agree it would be nice to have a clean example of this. That said—I think the question of using beaker-py versus the CLI is somewhat separate from whether we should continue the pattern of using beaker datasets to pipe the config into our jobs.

**Comment by gideonite** [comment]
> continue the pattern of using beaker datasets to pipe the config into our jobs.

Yeah I chatted with skjonsie about this and he seemed to think that this was still a good strategy.

**Comment by gideonite** [comment]
This seems low on the priority queue. Closing to keep the list neat.
